import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {createClient} from "@libsql/client";
import {TursoIdentityRepository} from "./turso-identity-repository.ts";

async function fixture(){const client=createClient({url:"file::memory:"});for(const migration of ["0001_website_identity.sql","0002_password_recovery_state.sql","0003_admin_control_plane.sql"]){await client.executeMultiple(await readFile(new URL(`../../../turso/migrations/${migration}`,import.meta.url),"utf8"))}return{client,repo:new TursoIdentityRepository(client),async close(){client.close()}}}
test("new user provisioning creates canonical UUID and Clerk mapping",async()=>{const f=await fixture();try{const id=await f.repo.createApplicationUser({clerkUserId:"user_new",email:"New@Example.com",username:"NewPlayer"});assert.match(id,/^[0-9a-f-]{36}$/);assert.equal((await f.repo.getUserByClerkId("user_new"))?.id,id);assert.equal((await f.repo.getUserByApplicationId(id))?.email,"new@example.com")}finally{await f.close()}});
test("database enforces normalized username and email uniqueness under concurrency",async()=>{const f=await fixture();try{const results=await Promise.allSettled([f.repo.createApplicationUser({clerkUserId:"user_a",email:"a@example.com",username:"SameName"}),f.repo.createApplicationUser({clerkUserId:"user_b",email:"b@example.com",username:"samename"})]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);await assert.rejects(()=>f.repo.createApplicationUser({clerkUserId:"user_c",email:"A@EXAMPLE.COM",username:"Different"}))}finally{await f.close()}});
test("mapping uniqueness prevents Clerk or application UUID reuse",async()=>{const f=await fixture();try{const id=await f.repo.createApplicationUser({clerkUserId:"user_a",email:"a@example.com",username:"Alpha"});await assert.rejects(()=>f.repo.mapClerkIdentity("user_b",id));await assert.rejects(()=>f.repo.mapClerkIdentity("user_a","missing"))}finally{await f.close()}});
test("legacy import preserves canonical Supabase UUID",async()=>{const f=await fixture();try{const legacy="11111111-2222-4333-8444-555555555555";const id=await f.repo.createApplicationUser({clerkUserId:"user_legacy",email:"legacy@example.com",username:"Legacy",applicationUserId:legacy,legacySupabaseUserId:legacy,role:"ADMIN",tier:"PREMIUM",createdAt:"2024-01-01T00:00:00.000Z"});assert.equal(id,legacy);assert.deepEqual(await f.repo.getRole("user_legacy"),"ADMIN");assert.deepEqual(await f.repo.getTier("user_legacy"),"PREMIUM")}finally{await f.close()}});
test("passwordless legacy routing is server-authoritative until completion",async()=>{const f=await fixture();try{const id=await f.repo.createApplicationUser({clerkUserId:"user_recovery",email:"legacy@example.com",username:"Legacy"});await f.client.execute({sql:"UPDATE auth_identity_mapping SET migration_state='PASSWORD_RECOVERY_REQUIRED',migrated_at=NULL WHERE clerk_user_id=?",args:["user_recovery"]});assert.deepEqual(await f.repo.getLoginRouting("LEGACY@example.com"),{recoveryRequired:true,email:"legacy@example.com"});assert.deepEqual(await f.repo.getLoginRouting("legacy"),{recoveryRequired:true,email:"legacy@example.com"});assert.deepEqual(await f.repo.getLoginRouting("unknown@example.com"),{recoveryRequired:false});await f.repo.completePasswordMigration("user_recovery");assert.deepEqual(await f.repo.getLoginRouting("legacy@example.com"),{recoveryRequired:false});assert.equal((await f.repo.getUserByApplicationId(id))?.username,"Legacy")}finally{await f.close()}});
test("ACTIVE users remain on normal password login",async()=>{const f=await fixture();try{await f.repo.createApplicationUser({clerkUserId:"user_active",email:"active@example.com",username:"Active"});assert.deepEqual(await f.repo.getLoginRouting("active@example.com"),{recoveryRequired:false});await f.repo.completePasswordMigration("user_active");assert.deepEqual(await f.repo.getLoginRouting("Active"),{recoveryRequired:false})}finally{await f.close()}});
test("unavailable Turso rejects cleanly",async()=>{const client=createClient({url:"http://127.0.0.1:1"});const repo=new TursoIdentityRepository(client);await assert.rejects(()=>repo.isUsernameAvailable("ValidName"));client.close()});
test("admin list/detail are server-authorized and paginated",async()=>{const f=await fixture();try{const admin=await f.repo.createApplicationUser({clerkUserId:"admin",email:"admin@example.com",username:"Admin",role:"ADMIN"});const user=await f.repo.createApplicationUser({clerkUserId:"user",email:"user@example.com",username:"Player"});assert.equal((await f.repo.listAdminUsers({actorApplicationUserId:admin,search:"player",limit:25,offset:0})).users[0].id,user);assert.equal(await f.repo.getAdminUser(user,admin),null)}finally{await f.close()}});
test("admin mutations preserve audit and final-admin protection",async()=>{const f=await fixture();try{const admin=await f.repo.createApplicationUser({clerkUserId:"admin",email:"admin@example.com",username:"Admin",role:"ADMIN"});const user=await f.repo.createApplicationUser({clerkUserId:"user",email:"user@example.com",username:"Player"});await f.repo.adminSetTier(admin,user,"PREMIUM");await f.repo.adminSetUsername(admin,user,"Renamed");await f.repo.adminSetEntitlement(admin,user,"browser.mode","DISABLED");assert.equal((await f.repo.getAdminUser(admin,user))?.tier,"PREMIUM");assert.equal((await f.repo.getAdminOverrides(admin,user))[0].enabled,false);assert.equal((await f.repo.getAdminAudit(admin,user)).length,3);await assert.rejects(()=>f.repo.adminSetRole(admin,admin,"USER"),/ADMIN_MUTATION_REJECTED/)}finally{await f.close()}});
test("concurrent demotions can never remove every administrator",async()=>{const f=await fixture();try{const a=await f.repo.createApplicationUser({clerkUserId:"a",email:"a@example.com",username:"AdminA",role:"ADMIN"});const b=await f.repo.createApplicationUser({clerkUserId:"b",email:"b@example.com",username:"AdminB",role:"ADMIN"});const results=await Promise.allSettled([f.repo.adminSetRole(a,a,"USER"),f.repo.adminSetRole(b,b,"USER")]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);const count=await f.client.execute("SELECT COUNT(*) AS count FROM app_users WHERE role='ADMIN'");assert.equal(Number(count.rows[0].count),1)}finally{await f.close()}});
