import { randomUUID } from "node:crypto";
import { createClient, type Client, type Row } from "@libsql/client";
import type { AdminAuditEntry, AdminUser, CreateApplicationUserInput, EntitlementOverride, IdentityProfile, IdentityRepository, MigrationState, UserRole, UserTier } from "./identity-repository";
const QUERY_TIMEOUT_MS=10_000;
export const normalizeUsername=(value:string)=>value.trim();
export const normalizeEmail=(value:string)=>value.trim().toLowerCase();
export const validUsername=(value:string)=>{const v=normalizeUsername(value);return v.length>=3&&v.length<=32&&/^[\p{L}\p{N}_.-]+$/u.test(v)};
function bounded<T>(operation:Promise<T>):Promise<T>{let timer:ReturnType<typeof setTimeout>;return Promise.race([operation,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error("Identity database timed out")),QUERY_TIMEOUT_MS)})]).finally(()=>clearTimeout(timer))}
function profile(row:Row|undefined):IdentityProfile|null{if(!row)return null;return{id:String(row.id),email:String(row.email),username:String(row.username),role:String(row.role) as UserRole,tier:String(row.tier) as UserTier,created_at:String(row.created_at),updated_at:String(row.updated_at),legacy_supabase_user_id:row.legacy_supabase_user_id==null?null:String(row.legacy_supabase_user_id)}}
function adminUser(row:Row|undefined):AdminUser|null{const value=profile(row);if(!value||!row)return null;return{...value,migration_state:String(row.migration_state) as MigrationState,total_count:row.total_count==null?undefined:Number(row.total_count)}}
const adminExistsSql="EXISTS(SELECT 1 FROM app_users actor JOIN auth_identity_mapping am ON am.application_user_id=actor.id WHERE actor.id=? AND actor.role='ADMIN' AND am.migration_state='ACTIVE')";
function mutationError(kind:"role"|"other"){throw new Error(kind==="role"?"ADMIN_MUTATION_REJECTED":"ADMIN_MUTATION_REJECTED")}
export class TursoIdentityRepository implements IdentityRepository {
  private readonly client:Client;
  constructor(client:Client){this.client=client}
  async getUserByClerkId(clerkUserId:string){const r=await bounded(this.client.execute({sql:`SELECT u.* FROM app_users u JOIN auth_identity_mapping m ON m.application_user_id=u.id WHERE m.clerk_user_id=? AND m.migration_state='ACTIVE'`,args:[clerkUserId]}));return profile(r.rows[0])}
  async getUserByApplicationId(id:string){const r=await bounded(this.client.execute({sql:"SELECT * FROM app_users WHERE id=?",args:[id]}));return profile(r.rows[0])}
  async isUsernameAvailable(username:string){if(!validUsername(username))return false;const r=await bounded(this.client.execute({sql:"SELECT 1 FROM app_users WHERE username_normalized=? LIMIT 1",args:[normalizeUsername(username).toLowerCase()]}));return r.rows.length===0}
  async createApplicationUser(input:CreateApplicationUserInput){if(!validUsername(input.username)||!input.clerkUserId.trim()||!normalizeEmail(input.email))throw new Error("Invalid identity profile");const id=input.applicationUserId??randomUUID();const now=input.createdAt??new Date().toISOString();const username=normalizeUsername(input.username);const email=normalizeEmail(input.email);await bounded(this.client.batch([
    {sql:"INSERT INTO app_users(id,email,email_normalized,username,username_normalized,role,tier,created_at,updated_at,legacy_supabase_user_id) VALUES(?,?,?,?,?,?,?,?,?,?)",args:[id,email,email,username,username.toLowerCase(),input.role??"USER",input.tier??"FREE",now,now,input.legacySupabaseUserId??null]},
    {sql:"INSERT INTO auth_identity_mapping(clerk_user_id,application_user_id,migration_state,created_at,migrated_at) VALUES(?,?,?,?,?)",args:[input.clerkUserId,id,"ACTIVE",now,now]},
  ],"write"));return id}
  async mapClerkIdentity(clerkUserId:string,applicationUserId:string,migrationState:MigrationState="ACTIVE"){const now=new Date().toISOString();await bounded(this.client.execute({sql:"INSERT INTO auth_identity_mapping(clerk_user_id,application_user_id,migration_state,created_at,migrated_at) VALUES(?,?,?,?,?)",args:[clerkUserId,applicationUserId,migrationState,now,migrationState==="ACTIVE"?now:null]}))}
  async getLoginRouting(identifier:string){const normalized=identifier.trim().toLowerCase();if(!normalized)return{recoveryRequired:false};const r=await bounded(this.client.execute({sql:`SELECT u.email,m.migration_state FROM app_users u JOIN auth_identity_mapping m ON m.application_user_id=u.id WHERE u.email_normalized=? OR u.username_normalized=? LIMIT 1`,args:[normalized,normalized]}));const row=r.rows[0];return row&&String(row.migration_state)==="PASSWORD_RECOVERY_REQUIRED"?{recoveryRequired:true,email:String(row.email)}:{recoveryRequired:false}}
  async completePasswordMigration(clerkUserId:string){const now=new Date().toISOString();const result=await bounded(this.client.execute({sql:"UPDATE auth_identity_mapping SET migration_state='ACTIVE',migrated_at=? WHERE clerk_user_id=? AND migration_state IN ('PASSWORD_RECOVERY_REQUIRED','ACTIVE')",args:[now,clerkUserId]}));if(result.rowsAffected!==1)throw new Error("Recovery mapping not found")}
  async getRole(clerkUserId:string){return(await this.getUserByClerkId(clerkUserId))?.role??null}
  async getTier(clerkUserId:string){return(await this.getUserByClerkId(clerkUserId))?.tier??null}
  async updateProfile(clerkUserId:string,input:{username:string}){if(!validUsername(input.username))throw new Error("Invalid username");const user=await this.getUserByClerkId(clerkUserId);if(!user)throw new Error("Profile not found");const username=normalizeUsername(input.username);await bounded(this.client.execute({sql:"UPDATE app_users SET username=?,username_normalized=?,updated_at=? WHERE id=?",args:[username,username.toLowerCase(),new Date().toISOString(),user.id]}))}
  async listAdminUsers(input:{actorApplicationUserId:string;search?:string;role?:UserRole;tier?:UserTier;limit:number;offset:number}){const limit=Math.max(1,Math.min(100,input.limit));const offset=Math.max(0,input.offset);const search=`%${(input.search??"").trim().toLowerCase()}%`;const result=await bounded(this.client.execute({sql:`SELECT u.*,m.migration_state,COUNT(*) OVER() AS total_count FROM app_users u JOIN auth_identity_mapping m ON m.application_user_id=u.id WHERE ${adminExistsSql} AND (?='' OR u.email_normalized LIKE ? OR u.username_normalized LIKE ?) AND (?='' OR u.role=?) AND (?='' OR u.tier=?) ORDER BY u.created_at DESC LIMIT ? OFFSET ?`,args:[input.actorApplicationUserId,input.search?.trim()??"",search,search,input.role??"",input.role??"",input.tier??"",input.tier??"",limit,offset]}));const users=result.rows.map(row=>adminUser(row)).filter((row):row is AdminUser=>row!==null);return{users,total:users[0]?.total_count??0}}
  async getAdminUser(actorId:string,targetId:string){const result=await bounded(this.client.execute({sql:`SELECT u.*,m.migration_state FROM app_users u JOIN auth_identity_mapping m ON m.application_user_id=u.id WHERE ${adminExistsSql} AND u.id=?`,args:[actorId,targetId]}));return adminUser(result.rows[0])}
  async getAdminOverrides(actorId:string,targetId:string){const result=await bounded(this.client.execute({sql:`SELECT feature_id,enabled,updated_at FROM entitlement_overrides WHERE ${adminExistsSql} AND application_user_id=? ORDER BY feature_id`,args:[actorId,targetId]}));return result.rows.map(row=>({feature_id:String(row.feature_id),enabled:Number(row.enabled)===1,updated_at:String(row.updated_at)} satisfies EntitlementOverride))}
  async getAdminAudit(actorId:string,targetId:string){const result=await bounded(this.client.execute({sql:`SELECT id,actor_application_user_id,target_application_user_id,action,old_value,new_value,created_at FROM admin_audit_log WHERE ${adminExistsSql} AND target_application_user_id=? ORDER BY created_at DESC LIMIT 100`,args:[actorId,targetId]}));return result.rows.map(row=>({id:String(row.id),actor_application_user_id:String(row.actor_application_user_id),target_application_user_id:String(row.target_application_user_id),action:String(row.action),old_value:row.old_value==null?null:String(row.old_value),new_value:row.new_value==null?null:String(row.new_value),created_at:String(row.created_at)} satisfies AdminAuditEntry))}
  async adminSetRole(actorId:string,targetId:string,role:UserRole){const now=new Date().toISOString();const condition=`${adminExistsSql} AND EXISTS(SELECT 1 FROM app_users t WHERE t.id=? AND t.role<>? AND (t.role<>'ADMIN' OR ?='ADMIN' OR (SELECT COUNT(*) FROM app_users WHERE role='ADMIN')>1))`;const results=await bounded(this.client.batch([{sql:`INSERT INTO admin_audit_log(id,actor_application_user_id,target_application_user_id,action,old_value,new_value,created_at) SELECT ?,?,?, 'role_change',role,?,? FROM app_users WHERE id=? AND ${condition}`,args:[randomUUID(),actorId,targetId,role,now,targetId,actorId,targetId,role,role]},{sql:`UPDATE app_users SET role=?,updated_at=? WHERE id=? AND ${condition}`,args:[role,now,targetId,actorId,targetId,role,role]}],"write"));if(results[1].rowsAffected!==1)mutationError("role")}
  async adminSetTier(actorId:string,targetId:string,tier:UserTier){const now=new Date().toISOString();const condition=`${adminExistsSql} AND EXISTS(SELECT 1 FROM app_users t WHERE t.id=? AND t.tier<>?)`;const results=await bounded(this.client.batch([{sql:`INSERT INTO admin_audit_log(id,actor_application_user_id,target_application_user_id,action,old_value,new_value,created_at) SELECT ?,?,?, 'tier_change',tier,?,? FROM app_users WHERE id=? AND ${condition}`,args:[randomUUID(),actorId,targetId,tier,now,targetId,actorId,targetId,tier]},{sql:`UPDATE app_users SET tier=?,updated_at=? WHERE id=? AND ${condition}`,args:[tier,now,targetId,actorId,targetId,tier]}],"write"));if(results[1].rowsAffected!==1)mutationError("other")}
  async adminSetUsername(actorId:string,targetId:string,value:string){if(!validUsername(value))throw new Error("INVALID_USERNAME");const username=normalizeUsername(value);const now=new Date().toISOString();const condition=`${adminExistsSql} AND EXISTS(SELECT 1 FROM app_users t WHERE t.id=? AND t.username_normalized<>?)`;const results=await bounded(this.client.batch([{sql:`INSERT INTO admin_audit_log(id,actor_application_user_id,target_application_user_id,action,old_value,new_value,created_at) SELECT ?,?,?, 'username_change',username,?,? FROM app_users WHERE id=? AND ${condition}`,args:[randomUUID(),actorId,targetId,username,now,targetId,actorId,targetId,username.toLowerCase()]},{sql:`UPDATE app_users SET username=?,username_normalized=?,updated_at=? WHERE id=? AND ${condition}`,args:[username,username.toLowerCase(),now,targetId,actorId,targetId,username.toLowerCase()]}],"write"));if(results[1].rowsAffected!==1)mutationError("other")}
  async adminSetEntitlement(actorId:string,targetId:string,featureId:string,state:"DEFAULT"|"ENABLED"|"DISABLED"){const now=new Date().toISOString();const old=`COALESCE((SELECT CASE enabled WHEN 1 THEN 'ENABLED' ELSE 'DISABLED' END FROM entitlement_overrides WHERE application_user_id=? AND feature_id=?),'DEFAULT')`;const allowed=`${adminExistsSql} AND EXISTS(SELECT 1 FROM app_users WHERE id=?)`;const audit={sql:`INSERT INTO admin_audit_log(id,actor_application_user_id,target_application_user_id,action,old_value,new_value,created_at) SELECT ?,?,?, 'entitlement_change',${old},?,? WHERE ${allowed}`,args:[randomUUID(),actorId,targetId,targetId,featureId,state,now,actorId,targetId]};const change=state==="DEFAULT"?{sql:`DELETE FROM entitlement_overrides WHERE application_user_id=? AND feature_id=? AND ${adminExistsSql}`,args:[targetId,featureId,actorId]}:{sql:`INSERT INTO entitlement_overrides(application_user_id,feature_id,enabled,updated_at) SELECT ?,?,?,? WHERE ${adminExistsSql} ON CONFLICT(application_user_id,feature_id) DO UPDATE SET enabled=excluded.enabled,updated_at=excluded.updated_at`,args:[targetId,featureId,state==="ENABLED"?1:0,now,actorId]};const results=await bounded(this.client.batch([audit,change],"write"));if(results[0].rowsAffected!==1)mutationError("other")}
}
let singleton:TursoIdentityRepository|undefined;
export function getIdentityRepository(){if(singleton)return singleton;const url=process.env.TURSO_DATABASE_URL;if(!url)throw new Error("TURSO_DATABASE_URL is required");const authToken=process.env.TURSO_AUTH_TOKEN;if(!url.startsWith("file:")&&!authToken)throw new Error("TURSO_AUTH_TOKEN is required");singleton=new TursoIdentityRepository(createClient({url,authToken}));return singleton}
