import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
import {createClient} from "@libsql/client";
import {TursoIdentityRepository} from "./turso-identity-repository.ts";

async function fixture(){const client=createClient({url:"file::memory:"});const schema=await readFile(new URL("../../../turso/migrations/0001_website_identity.sql",import.meta.url),"utf8");await client.executeMultiple(schema);return{client,repo:new TursoIdentityRepository(client),async close(){client.close()}}}
test("new user provisioning creates canonical UUID and Clerk mapping",async()=>{const f=await fixture();try{const id=await f.repo.createApplicationUser({clerkUserId:"user_new",email:"New@Example.com",username:"NewPlayer"});assert.match(id,/^[0-9a-f-]{36}$/);assert.equal((await f.repo.getUserByClerkId("user_new"))?.id,id);assert.equal((await f.repo.getUserByApplicationId(id))?.email,"new@example.com")}finally{await f.close()}});
test("database enforces normalized username and email uniqueness under concurrency",async()=>{const f=await fixture();try{const results=await Promise.allSettled([f.repo.createApplicationUser({clerkUserId:"user_a",email:"a@example.com",username:"SameName"}),f.repo.createApplicationUser({clerkUserId:"user_b",email:"b@example.com",username:"samename"})]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);await assert.rejects(()=>f.repo.createApplicationUser({clerkUserId:"user_c",email:"A@EXAMPLE.COM",username:"Different"}))}finally{await f.close()}});
test("mapping uniqueness prevents Clerk or application UUID reuse",async()=>{const f=await fixture();try{const id=await f.repo.createApplicationUser({clerkUserId:"user_a",email:"a@example.com",username:"Alpha"});await assert.rejects(()=>f.repo.mapClerkIdentity("user_b",id));await assert.rejects(()=>f.repo.mapClerkIdentity("user_a","missing"))}finally{await f.close()}});
test("legacy import preserves canonical Supabase UUID",async()=>{const f=await fixture();try{const legacy="11111111-2222-4333-8444-555555555555";const id=await f.repo.createApplicationUser({clerkUserId:"user_legacy",email:"legacy@example.com",username:"Legacy",applicationUserId:legacy,legacySupabaseUserId:legacy,role:"ADMIN",tier:"PREMIUM",createdAt:"2024-01-01T00:00:00.000Z"});assert.equal(id,legacy);assert.deepEqual(await f.repo.getRole("user_legacy"),"ADMIN");assert.deepEqual(await f.repo.getTier("user_legacy"),"PREMIUM")}finally{await f.close()}});
test("unavailable Turso rejects cleanly",async()=>{const client=createClient({url:"http://127.0.0.1:1"});const repo=new TursoIdentityRepository(client);await assert.rejects(()=>repo.isUsernameAvailable("ValidName"));client.close()});
