const GAME="26",MAX_IDS=5000,MAX_RESPONSE=128*1024,CACHE_TTL=5*60*1000,REQUESTS_PER_MINUTE=30;
const PROVIDER_ORIGIN="https://r2.fut.gg";
type PriceData={idx:{id0:number;d:number[]};blob:{p:Array<number|null>}};
const cache:{expiresAt:number;data:PriceData|null;pending:Promise<PriceData>|null}={expiresAt:0,data:null,pending:null};
const buckets=new Map<string,{startedAt:number;count:number}>();
export class BrowserPricingError extends Error{status:number;code:string;constructor(status:number,code:string,message:string){super(message);this.status=status;this.code=code;}}
export function validateResourceIds(value:unknown){if(!Array.isArray(value))throw new BrowserPricingError(400,"invalid_resource_ids","resourceIds must be an array.");if(value.length>MAX_IDS)throw new BrowserPricingError(400,"too_many_resource_ids",`At most ${MAX_IDS} resourceIds are accepted.`);const unique=new Set<number>();for(const id of value){if(!Number.isSafeInteger(id)||Number(id)<=0||Number(id)>999_999_999)throw new BrowserPricingError(400,"invalid_resource_id","Every resourceId must be a positive safe integer no greater than 999999999.");unique.add(Number(id));}return[...unique];}
export function consumeRateLimit(key:string,now=Date.now()){const current=buckets.get(key);if(!current||now-current.startedAt>=60_000){buckets.set(key,{startedAt:now,count:1});return;}if(++current.count>REQUESTS_PER_MINUTE)throw new BrowserPricingError(429,"rate_limited","Too many pricing requests.");}
async function json(url:string,timeout:number,fetchImpl:typeof fetch){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetchImpl(url,{signal:controller.signal,headers:{Accept:"application/json","User-Agent":"FUT-Forge-Browser/2.10.3"},cache:"no-store"});if(!response.ok)throw new BrowserPricingError(502,"provider_error","Pricing is temporarily unavailable.");return await response.json();}finally{clearTimeout(timer);}}
export async function loadPriceData(fetchImpl:typeof fetch=fetch,now=Date.now()):Promise<PriceData>{if(cache.data&&cache.expiresAt>now)return cache.data;if(cache.pending)return cache.pending;cache.pending=(async()=>{const manifest=await json(`${PROVIDER_ORIGIN}/${GAME}/manifest.json`,15_000,fetchImpl) as Record<string,unknown>,version=manifest._version,indexHash=manifest["player-prices-index"],priceHash=manifest["player-prices-ps5-dyn"];if(version==null||typeof indexHash!=="string"||typeof priceHash!=="string")throw new BrowserPricingError(502,"provider_schema","Pricing is temporarily unavailable.");const [idx,blob]=await Promise.all([json(`${PROVIDER_ORIGIN}/${GAME}/player-prices-index.v${encodeURIComponent(String(version))}.${encodeURIComponent(indexHash)}.json`,30_000,fetchImpl),json(`${PROVIDER_ORIGIN}/${GAME}/player-prices-ps5-dyn.v${encodeURIComponent(String(version))}.${encodeURIComponent(priceHash)}.json`,30_000,fetchImpl)]) as [{id0?:unknown;d?:unknown},{p?:unknown}];if(!Number.isSafeInteger(idx.id0)||!Array.isArray(idx.d)||!idx.d.every(Number.isSafeInteger)||!Array.isArray(blob.p)||blob.p.length!==idx.d.length+1)throw new BrowserPricingError(502,"provider_schema","Pricing is temporarily unavailable.");const data={idx:idx as PriceData["idx"],blob:blob as PriceData["blob"]};cache.data=data;cache.expiresAt=Date.now()+CACHE_TTL;return data;})();try{return await cache.pending;}finally{cache.pending=null;}}
export function selectPrices(resourceIds:number[],data:PriceData){const wanted=new Set(resourceIds),prices:Record<string,number>={};let id=data.idx.id0;const take=(candidate:unknown)=>{const price=Number(candidate);if(wanted.has(id)&&Number.isSafeInteger(price)&&price>0)prices[String(id)]=price;};take(data.blob.p[0]);for(let i=0;i<data.idx.d.length;i++){id+=data.idx.d[i];take(data.blob.p[i+1]);}const encoded=JSON.stringify({ok:true,prices});if(Buffer.byteLength(encoded)>MAX_RESPONSE)throw new BrowserPricingError(413,"response_too_large","Pricing response exceeds the configured limit.");return encoded;}
export function resetBrowserPricingStateForTests(){cache.data=null;cache.expiresAt=0;cache.pending=null;buckets.clear();}
