export const locales = ["en", "it"] as const;
export type Locale = (typeof locales)[number];

export const PRODUCT = {
  name: "FUT Forge",
  desktopName: "FUT Forge Desktop",
  version: "2.10.0",
  displayVersion: "2.10",
  email: "hello@futforge.app",
  wordmark: ["FUT", "FORGE"],
} as const;

export const siteCopy = {
  title: "FUT Forge — The desktop workspace for Ultimate Team",
  description: "Plan SBCs and Evolutions in one focused desktop application. Fewer tabs. Better decisions.",
  applicationName: "FUT Forge Desktop",
  category: "gaming",
  url: "https://futforge.vercel.app",
} as const;

export const copy = {
  en: {
    localeName: "English",
    languageShort: "EN",
    nav: {
      aria: "Main navigation",
      home: "FUT Forge home",
      desktop: "Desktop",
      features: "Features",
      roadmap: "Roadmap",
      download: "Download",
      app: "Web App",
      cta: "Get FUT Forge",
      open: "Open navigation",
      close: "Close navigation",
      language: "Change language",
    },
    hero: {
      release: "FUT Forge Desktop v2.10",
      releaseNote: "A desktop workspace for Ultimate Team",
      words: ["BUILD", "OPTIMIZE", "DOMINATE"],
      lead: "Your Ultimate Team workspace. On desktop.",
      body: "Plan SBCs and Evolutions in one focused application. Fewer tabs. Better decisions.",
      primary: "Get FUT Forge",
      primaryMeta: "Windows 10 & 11",
      free: "Free",
      secondary: "Explore the workspace",
      secondaryMeta: "See real product screens",
      trust: ["Native Windows application", "Built for desktop", "Community-led"],
      proof: [
        ["Native", "Windows desktop application"],
        ["Local-first", "processing"],
        ["Automatic", "GitHub release updates"],
        ["Community", "driven development"],
      ],
    },
    boot: {
      aria: "FUT Forge Desktop launch sequence",
      version: "FUT Forge Desktop v2.10",
      tagline: "Build. Optimize. Dominate.",
      ready: "Workspace ready",
      steps: [
        "Initializing workspace...",
        "Loading chemistry engine...",
        "Loading SBC Solver...",
        "Loading Desktop Workspace...",
        "Loading Evolution Engine...",
        "Synchronizing club...",
        "Ready.",
      ],
      secure: "Secure startup",
    },
    features: {
      label: "Inside the workspace",
      title: "Two focused workflows.",
      titleMuted: "One desktop workspace.",
      intro: "Real captures from the current FUT Forge application. Purpose-built for Ultimate Team, without the browser clutter.",
      stories: [
        {
          eyebrow: "SBC Solver",
          title: "Solve the challenge. Keep the value.",
          text: "Read every requirement, shape the solution, and stay focused from the first squad to submission.",
          alt: "FUT Forge SBC Solver desktop workspace",
          points: ["Live challenge catalogue", "Requirements at a glance", "A focused desktop workflow"],
        },
        {
          eyebrow: "EVO Builder",
          title: "Plan the player before the grind.",
          text: "Compare Evolution routes, understand each outcome, and commit only when the path is right.",
          alt: "FUT Forge EVO Builder desktop workspace",
          points: ["Player-first planning", "Clear route comparison", "Saved Evolution paths"],
        },
      ],
    },
    frame: {
      desktop: "Desktop",
      captured: "Captured in FUT Forge v2.10",
      platform: "Windows desktop application",
      aria: "Current FUT Forge product capture",
    },
    download: {
      label: "FUT Forge Desktop",
      title: "Your workspace is ready.",
      body: "One application for the Ultimate Team decisions that matter. Free to download. Built for Windows.",
      button: "Download for Windows",
      unavailable: "Installer temporarily unavailable",
      platform: "Windows 10/11 · 64-bit",
      updates: "Automatic updates",
      version: "Version",
      filename: "Installer",
      released: "Released",
      latest: "Latest release",
    },
    roadmap: {
      label: "Product roadmap",
      title: "Built in public.",
      titleMuted: "Scoped with care.",
      body: "Shipping work is shown as shipped. Future milestones appear only after their scope is confirmed.",
      steps: [
        { phase: "Now", title: "SBC Solver and EVO Builder", text: "Available now in FUT Forge v2.10." },
        { phase: "Next", title: "Next milestone", text: "Scope will be published when development is confirmed." },
        { phase: "Later", title: "Long-term direction", text: "Reserved for product plans validated with the community." },
      ],
    },
    footer: {
      tagline: "A desktop workspace for Ultimate Team.",
      features: "Features",
      roadmap: "Roadmap",
      download: "Download",
      contact: "GitHub",
      contactAria: "FUT Forge GitHub repository (opens in a new tab)",
      rights: "© 2026 FUT Forge. All rights reserved.",
      disclaimer: "Not affiliated with EA Sports or Electronic Arts.",
    },
    downloadPage: {
      metaTitle: "Download FUT Forge Desktop", metaDescription: "Download the official FUT Forge installer for Windows 10 and 11.",
      eyebrow: "FUT Forge Desktop", heroTitle: "Your Ultimate Team workspace. On Windows.", heroBody: "Plan SBCs and Evolutions in one focused desktop application.",
      stable: "Stable", beta: "Beta", version: "Version", released: "Released", windows: "Windows 10/11", architecture: "64-bit", architectureLabel: "Architecture", free: "Free", updates: "Automatic updates",
      download: "Download FUT Forge", unavailable: "Installer temporarily unavailable", unavailableHelp: "The official installer could not be verified. Please try again shortly.",
      releaseTitle: "Current release", filename: "Installer", size: "Size", checksum: "SHA-256", copyChecksum: "Copy SHA-256 checksum", copied: "Copied", officialRelease: "View official GitHub Release",
      officialReleaseAria: "View official GitHub release (opens in a new tab)",
      whatsNew: "What’s new", fallbackNotes: ["Improved SBC solving reliability", "Better desktop stability", "Faster update pipeline", "Internal performance improvements"],
      requirements: "System requirements", requirementItems: ["Windows 10 or Windows 11", "64-bit operating system", "Internet connection"],
      installation: "Installation", installSteps: ["Download the official installer", "Run the installer", "Launch FUT Forge"],
      trustItems: ["Official GitHub release", "SHA-256 verified", "No installer bundling", "Digitally identical to GitHub release"],
      security: "Security and trust", securityItems: ["Published through the official FUT Forge GitHub release", "SHA-256 checksum provided for integrity checks", "Automatic updates included"],
      preview: "Application preview", previewBody: "A focused workspace for planning SBCs without browser clutter.", previewAlt: "FUT Forge SBC Solver desktop workspace",
      faq: "Frequently asked questions", faqs: [
        ["Is FUT Forge free?", "Yes. FUT Forge Desktop is free."], ["Does it support Windows 11?", "Yes. It supports 64-bit Windows 10 and 11."],
        ["How do updates work?", "The app checks for official FUT Forge releases automatically."], ["Where is the installer hosted?", "In the official FUT Forge Releases repository on GitHub."],
        ["Is a Mac version available?", "No. The official repository currently provides a Windows installer only."],
      ], finalTitle: "Ready to get started?", finalBody: "Download the latest official Windows release.",
    },
    app: {
      landing: {
        eyebrow: "FUT Forge Web App",
        title: "Tools, in the browser.",
        titleMuted: "Built for Ultimate Team.",
        intro: "Early web tools for Ultimate Team, built with the same care as FUT Forge Desktop. Starting with one working tool, growing from there.",
        openLabel: "Open",
        soonLabel: "Coming soon",
        tools: [
          { name: "Price", description: "Search a player or card and see its current market price.", status: "available", href: "/app/price" },
          { name: "EVO", description: "Search a player or card and find its best evolution path.", status: "available", href: "/app/evo" },
          { name: "Grade", description: "Enter a card's stats and see its FUT Forge Grade.", status: "available", href: "/app/grade" },
        ],
      },
      price: {
        eyebrow: "FUT Forge Web App",
        title: "Price",
        lead: "Search a player or card and see its current market price.",
        searchLabel: "Player or card name",
        searchPlaceholder: "e.g. Mbappé",
        searchButton: "Search",
        searchingButton: "Searching…",
        searchEmptyState: "Search for a player to see real cards and prices.",
        noResults: "No cards found for this search.",
        resultsHeading: "Results",
        ratingLabel: "OVR",
        selectCard: "View price",
        priceLoading: "Loading price…",
        priceNotFound: "No market price is available for this card right now.",
        priceValueLabel: "Market price",
        coinsSuffix: "coins",
        cachedLabel: "Served from cache",
        yes: "Yes",
        no: "No",
        backToResults: "Back to results",
        searchErrorTitle: "Couldn’t search for players",
        priceErrorTitle: "Couldn’t load the price",
        genericError: "Something went wrong. Please try again.",
        networkError: "Could not reach the Web App server.",
        disclaimer: "Prices are updated regularly and may lag the live in-game market slightly.",
      },
      grade: {
        eyebrow: "FUT Forge Web App",
        title: "Grade",
        lead: "Enter a card's stats and see its FUT Forge Grade out of 100.",
        statsHeading: "Stats",
        paceLabel: "PAC",
        shootingLabel: "SHO",
        passingLabel: "PAS",
        dribblingLabel: "DRI",
        defendingLabel: "DEF",
        physicalLabel: "PHY",
        detailsHeading: "Card details",
        positionLabel: "Position",
        positionPlaceholder: "Select position",
        skillMovesLabel: "Skill moves",
        weakFootLabel: "Weak foot",
        accelerateLabel: "AcceleRATE",
        accelerateNone: "Not specified",
        accelerateExplosive: "Explosive",
        accelerateLengthy: "Lengthy",
        accelerateControlled: "Controlled",
        submitButton: "Calculate grade",
        submittingButton: "Calculating…",
        emptyState: "Enter a card's stats to see its FUT Forge Grade.",
        resultLabel: "FUT Forge Grade",
        outOf: "/ 100",
        errorTitle: "Couldn’t calculate the grade",
        genericError: "Something went wrong. Please try again.",
        networkError: "Could not reach the Web App server.",
        validationError: "Enter a value between 0 and 99 for every stat.",
      },
      evo: {
        eyebrow: "FUT Forge Web App",
        title: "EVO",
        lead: "Search a player or card and find its best evolution path.",
        searchLabel: "Player or card name",
        searchPlaceholder: "e.g. Mbappé",
        searchButton: "Search",
        searchingButton: "Searching…",
        searchEmptyState: "Search for a player to explore its evolution paths.",
        noResults: "No cards found for this search.",
        resultsHeading: "Results",
        ratingLabel: "OVR",
        selectCard: "Select",
        backToResults: "Back to results",
        depthLabel: "Search depth",
        analyzeButton: "Find best path",
        analyzingButton: "Analyzing…",
        analysisEmptyState: "Choose a search depth and find this card's best evolution path.",
        noChainsFound: "No evolution paths were found for this card.",
        bestPathHeading: "Best evolution path",
        pathHeadingPrefix: "Path",
        pathsHeading: "Best chains",
        pathsSubheading: "Recommended evolution paths.",
        sortLabel: "Sort by",
        sortBest: "Best overall",
        sortMetaRating: "META Rating",
        sortOvr: "Final OVR",
        sortFewest: "Fewest EVOs",
        evoCountLabel: "EVOs",
        startingCardLabel: "Starting card",
        finalResultLabel: "Final result",
        stepFallbackName: "EVO",
        finalStatsLabel: "Final stats",
        boostsLabel: "Total boosts",
        metaRatingLabel: "META Rating",
        finalOvrLabel: "Final OVR",
        chainDetailsButton: "Chain details",
        chainsShowMore: "Show more chains",
        searchErrorTitle: "Couldn’t search for players",
        analysisErrorTitle: "Couldn’t analyze this card",
        genericError: "Something went wrong. Please try again.",
        networkError: "Could not reach the Web App server.",
        disclaimer: "Evolution paths and stats are based on the current, publicly available evolution catalogue and may change over time.",
        eligibleHeading: "Eligible evolutions",
        eligibleSubheading: "Evolutions this card can enter directly.",
        eligibleEmptyState: "No currently available evolutions accept this exact card.",
        eligibleFreeBadge: "Free",
        eligiblePaidBadge: "FC Points",
        eligibleRepeatableBadge: "Repeatable",
        eligibleEndsLabel: "Ends",
        eligibleRequirementsLabel: "Requirements",
        eligibleResultLabel: "Result",
        eligibleCoinsUnit: "coins",
        eligibleTokensUnit: "tokens",
        eligibleCostOr: "OR",
        eligibleCompatibleLabel: "compatible",
        eligibleFilterAll: "All",
        eligibleFilterFree: "Free",
        eligibleFilterPaid: "Paid",
        eligibleSearchPlaceholder: "Search evolution...",
        eligibleSortLabel: "Sort",
        eligibleSortBest: "Best result",
        eligibleSortOvr: "Final OVR",
        eligibleSortExpiry: "Expiry",
        eligibleSortCost: "Cost",
        eligibleShowingPrefix: "Showing",
        eligibleShowingOf: "of",
        eligibleShowingSuffix: "evolutions",
        eligibleShowMore: "Show 3 more",
        eligibleShowAll: "Show all",
        eligibleNoMatches: "No evolutions match these filters.",
        eligibleViewDetails: "View details",
        eligibleHideDetails: "Hide details",
      },
    },
    loading: "Loading FUT Forge",
  },
  it: {
    localeName: "Italiano",
    languageShort: "IT",
    nav: {
      aria: "Navigazione principale",
      home: "Torna all’inizio",
      desktop: "Desktop",
      features: "Funzionalità",
      roadmap: "Roadmap",
      download: "Download",
      app: "Web App",
      cta: "Scarica FUT Forge",
      open: "Apri il menu",
      close: "Chiudi il menu",
      language: "Cambia lingua",
    },
    hero: {
      release: "FUT Forge Desktop v2.10",
      releaseNote: "Il workspace per Ultimate Team. Su desktop.",
      words: ["CREA", "OTTIMIZZA", "DOMINA"],
      lead: "Tutto Ultimate Team. In un’unica applicazione desktop.",
      body: "SBC ed Evoluzioni, in un solo workspace. Meno schede. Più controllo.",
      primary: "Scarica FUT Forge",
      primaryMeta: "Windows 10 e 11",
      free: "Gratis",
      secondary: "Guarda FUT Forge in azione",
      secondaryMeta: "Esplora i workflow",
      trust: ["Applicazione desktop per Windows", "Workflow dedicati", "Sviluppata con la community"],
      proof: [
        ["Nativa", "app desktop Windows"],
        ["Local-first", "elaborazione"],
        ["Automatici", "aggiornamenti da GitHub"],
        ["Community", "sviluppo condiviso"],
      ],
    },
    boot: {
      aria: "Avvio di FUT Forge Desktop",
      version: "FUT Forge Desktop v2.10",
      tagline: "Crea. Ottimizza. Domina.",
      ready: "Workspace pronto",
      steps: [
        "Preparazione del workspace...",
        "Caricamento del motore dell’Intesa...",
        "Caricamento di SBC Solver...",
        "Caricamento del workspace desktop...",
        "Caricamento del motore Evoluzioni...",
        "Sincronizzazione del club...",
        "Pronto.",
      ],
      secure: "Avvio protetto",
    },
    features: {
      label: "Dentro il workspace",
      title: "Due workflow essenziali.",
      titleMuted: "Un solo workspace.",
      intro: "Screenshot reali dell’applicazione. SBC ed Evoluzioni, senza il caos del browser.",
      stories: [
        {
          eyebrow: "SBC Solver",
          title: "Completa la sfida. Proteggi il valore.",
          text: "Requisiti chiari, soluzione sotto controllo. Dalla prima rosa all’invio.",
          alt: "SBC Solver nel workspace desktop di FUT Forge",
          points: ["Catalogo SBC sempre aggiornato", "Requisiti chiari a colpo d’occhio", "Workflow senza distrazioni"],
        },
        {
          eyebrow: "EVO Builder",
          title: "Progetta il giocatore prima di iniziare.",
          text: "Confronta ogni percorso, valuta il risultato e scegli con chiarezza prima di iniziare.",
          alt: "EVO Builder nel workspace desktop di FUT Forge",
          points: ["Pianificazione centrata sul giocatore", "Confronto chiaro dei percorsi", "Evoluzioni salvate nel workspace"],
        },
      ],
    },
    frame: {
      desktop: "Desktop",
      captured: "Screenshot da FUT Forge v2.10",
      platform: "Applicazione desktop per Windows",
      aria: "Screenshot dell’applicazione FUT Forge",
    },
    download: {
      label: "FUT Forge Desktop",
      title: "Il tuo workspace è pronto.",
      body: "SBC ed Evoluzioni in un solo workspace. Gratis. Per Windows.",
      button: "Scarica per Windows",
      unavailable: "Download in arrivo",
      platform: "Windows 10/11 · 64 bit",
      updates: "Aggiornamenti automatici",
      version: "Versione",
      filename: "Installer",
      released: "Pubblicata il",
      latest: "Ultima versione",
    },
    roadmap: {
      label: "Roadmap",
      title: "Disponibile ora.",
      titleMuted: "Il resto, quando è pronto.",
      body: "Mostriamo ciò che esiste. Le prossime tappe entrano nella roadmap solo a sviluppo confermato.",
      steps: [
        { phase: "Ora", title: "SBC Solver ed EVO Builder", text: "Disponibili ora in FUT Forge v2.10." },
        { phase: "Prossimamente", title: "Prossimo aggiornamento", text: "Pubblicheremo i dettagli quando lo sviluppo sarà confermato." },
        { phase: "Più avanti", title: "Direzione futura", text: "Idee da valutare con la community prima di aggiungerle alla roadmap." },
      ],
    },
    footer: {
      tagline: "Il workspace per Ultimate Team. Su desktop.",
      features: "Funzionalità",
      roadmap: "Roadmap",
      download: "Download",
      contact: "GitHub",
      contactAria: "Repository GitHub di FUT Forge (si apre in una nuova scheda)",
      rights: "© 2026 FUT Forge. Tutti i diritti riservati.",
      disclaimer: "FUT Forge non è affiliato a EA Sports o Electronic Arts.",
    },
    downloadPage: {
      metaTitle: "Scarica FUT Forge Desktop", metaDescription: "Scarica l’installer ufficiale di FUT Forge per Windows 10 e 11.",
      eyebrow: "FUT Forge Desktop", heroTitle: "Il tuo workspace per Ultimate Team. Su Windows.", heroBody: "Pianifica SBC ed Evoluzioni in un’unica applicazione desktop.",
      stable: "Versione stabile", beta: "Beta", version: "Versione", released: "Pubblicata il", windows: "Windows 10/11", architecture: "64 bit", architectureLabel: "Architettura", free: "Gratis", updates: "Aggiornamenti automatici",
      download: "Scarica FUT Forge", unavailable: "Installer temporaneamente non disponibile", unavailableHelp: "Non è stato possibile verificare l’installer ufficiale. Riprova tra poco.",
      releaseTitle: "Release attuale", filename: "Installer", size: "Dimensione", checksum: "SHA-256", copyChecksum: "Copia il checksum SHA-256", copied: "Copiato", officialRelease: "Apri la release ufficiale su GitHub",
      officialReleaseAria: "Apri la release ufficiale su GitHub (si apre in una nuova scheda)",
      whatsNew: "Novità", fallbackNotes: ["Maggiore affidabilità nella risoluzione delle SBC", "Stabilità desktop migliorata", "Pipeline di aggiornamento più veloce", "Prestazioni interne ottimizzate"],
      requirements: "Requisiti di sistema", requirementItems: ["Windows 10 o Windows 11", "Sistema operativo a 64 bit", "Connessione a Internet"],
      installation: "Installazione", installSteps: ["Scarica l’installer ufficiale", "Avvia l’installer", "Apri FUT Forge"],
      trustItems: ["Release GitHub ufficiale", "Verifica SHA-256", "Nessun software aggiunto all’installer", "Identico alla release su GitHub"],
      security: "Sicurezza e affidabilità", securityItems: ["Pubblicato tramite la release GitHub ufficiale di FUT Forge", "Checksum SHA-256 per il controllo dell’integrità", "Aggiornamenti automatici inclusi"],
      preview: "Anteprima dell’applicazione", previewBody: "Un workspace essenziale per pianificare le SBC senza il caos del browser.", previewAlt: "SBC Solver nel workspace desktop di FUT Forge",
      faq: "Domande frequenti", faqs: [
        ["FUT Forge è gratuito?", "Sì. FUT Forge Desktop è gratuito."], ["È compatibile con Windows 11?", "Sì. Supporta Windows 10 e 11 a 64 bit."],
        ["Come funzionano gli aggiornamenti?", "L’app controlla automaticamente le release ufficiali di FUT Forge."], ["Dove è ospitato l’installer?", "Nel repository ufficiale FUT Forge Releases su GitHub."],
        ["Esiste una versione per Mac?", "No. Il repository ufficiale offre al momento solo l’installer Windows."],
      ], finalTitle: "Pronto per iniziare?", finalBody: "Scarica l’ultima release ufficiale per Windows.",
    },
    app: {
      landing: {
        eyebrow: "FUT Forge Web App",
        title: "Strumenti, nel browser.",
        titleMuted: "Pensato per Ultimate Team.",
        intro: "I primi strumenti web per Ultimate Team, costruiti con la stessa cura di FUT Forge Desktop. Si parte da un solo strumento funzionante e si cresce da lì.",
        openLabel: "Apri",
        soonLabel: "Prossimamente",
        tools: [
          { name: "Price", description: "Cerca un giocatore o una carta e scopri il suo prezzo di mercato attuale.", status: "available", href: "/app/price" },
          { name: "EVO", description: "Cerca un giocatore o una carta e trova il suo miglior percorso di evoluzione.", status: "available", href: "/app/evo" },
          { name: "Grade", description: "Inserisci le statistiche di una carta e scopri il suo FUT Forge Grade.", status: "available", href: "/app/grade" },
        ],
      },
      price: {
        eyebrow: "FUT Forge Web App",
        title: "Prezzi",
        lead: "Cerca un giocatore o una carta e scopri il suo prezzo di mercato attuale.",
        searchLabel: "Nome giocatore o carta",
        searchPlaceholder: "es. Mbappé",
        searchButton: "Cerca",
        searchingButton: "Ricerca in corso…",
        searchEmptyState: "Cerca un giocatore per vedere carte e prezzi reali.",
        noResults: "Nessuna carta trovata per questa ricerca.",
        resultsHeading: "Risultati",
        ratingLabel: "OVR",
        selectCard: "Vedi prezzo",
        priceLoading: "Caricamento prezzo…",
        priceNotFound: "Nessun prezzo di mercato disponibile per questa carta al momento.",
        priceValueLabel: "Prezzo di mercato",
        coinsSuffix: "monete",
        cachedLabel: "Servito dalla cache",
        yes: "Sì",
        no: "No",
        backToResults: "Torna ai risultati",
        searchErrorTitle: "Impossibile cercare giocatori",
        priceErrorTitle: "Impossibile caricare il prezzo",
        genericError: "Si è verificato un problema. Riprova.",
        networkError: "Impossibile raggiungere il server della Web App.",
        disclaimer: "I prezzi sono aggiornati regolarmente e potrebbero non coincidere esattamente con il mercato in tempo reale.",
      },
      grade: {
        eyebrow: "FUT Forge Web App",
        title: "Grade",
        lead: "Inserisci le statistiche di una carta e scopri il suo FUT Forge Grade su 100.",
        statsHeading: "Statistiche",
        paceLabel: "PAC",
        shootingLabel: "SHO",
        passingLabel: "PAS",
        dribblingLabel: "DRI",
        defendingLabel: "DEF",
        physicalLabel: "PHY",
        detailsHeading: "Dettagli carta",
        positionLabel: "Posizione",
        positionPlaceholder: "Seleziona posizione",
        skillMovesLabel: "Skill move",
        weakFootLabel: "Piede debole",
        accelerateLabel: "AcceleRATE",
        accelerateNone: "Non specificato",
        accelerateExplosive: "Explosive",
        accelerateLengthy: "Lengthy",
        accelerateControlled: "Controlled",
        submitButton: "Calcola grade",
        submittingButton: "Calcolo in corso…",
        emptyState: "Inserisci le statistiche di una carta per vedere il suo FUT Forge Grade.",
        resultLabel: "FUT Forge Grade",
        outOf: "/ 100",
        errorTitle: "Impossibile calcolare il grade",
        genericError: "Si è verificato un problema. Riprova.",
        networkError: "Impossibile raggiungere il server della Web App.",
        validationError: "Inserisci un valore tra 0 e 99 per ogni statistica.",
      },
      evo: {
        eyebrow: "FUT Forge Web App",
        title: "EVO",
        lead: "Cerca un giocatore o una carta e trova il suo miglior percorso di evoluzione.",
        searchLabel: "Nome giocatore o carta",
        searchPlaceholder: "es. Mbappé",
        searchButton: "Cerca",
        searchingButton: "Ricerca in corso…",
        searchEmptyState: "Cerca un giocatore per esplorare i suoi percorsi di evoluzione.",
        noResults: "Nessuna carta trovata per questa ricerca.",
        resultsHeading: "Risultati",
        ratingLabel: "OVR",
        selectCard: "Seleziona",
        backToResults: "Torna ai risultati",
        depthLabel: "Profondità di ricerca",
        analyzeButton: "Trova il miglior percorso",
        analyzingButton: "Analisi in corso…",
        analysisEmptyState: "Scegli una profondità di ricerca e trova il miglior percorso di evoluzione per questa carta.",
        noChainsFound: "Non è stato trovato alcun percorso di evoluzione per questa carta.",
        bestPathHeading: "Miglior percorso di evoluzione",
        pathHeadingPrefix: "Percorso",
        pathsHeading: "Catene migliori",
        pathsSubheading: "Percorsi di evoluzione consigliati.",
        sortLabel: "Ordina per",
        sortBest: "Migliore complessivo",
        sortMetaRating: "META Rating",
        sortOvr: "OVR finale",
        sortFewest: "Meno EVO",
        evoCountLabel: "EVO",
        startingCardLabel: "Carta di partenza",
        finalResultLabel: "Risultato finale",
        stepFallbackName: "EVO",
        finalStatsLabel: "Statistiche finali",
        boostsLabel: "Bonus totali",
        metaRatingLabel: "META Rating",
        finalOvrLabel: "OVR finale",
        chainDetailsButton: "Dettagli catena",
        chainsShowMore: "Mostra altre catene",
        searchErrorTitle: "Impossibile cercare giocatori",
        analysisErrorTitle: "Impossibile analizzare questa carta",
        genericError: "Si è verificato un problema. Riprova.",
        networkError: "Impossibile raggiungere il server della Web App.",
        disclaimer: "I percorsi di evoluzione e le statistiche si basano sul catalogo evoluzioni pubblicamente disponibile e possono cambiare nel tempo.",
        eligibleHeading: "Evoluzioni disponibili",
        eligibleSubheading: "Evoluzioni che questa carta può iniziare direttamente.",
        eligibleEmptyState: "Nessuna evoluzione attualmente disponibile accetta questa carta esatta.",
        eligibleFreeBadge: "Gratis",
        eligiblePaidBadge: "FC Points",
        eligibleRepeatableBadge: "Ripetibile",
        eligibleEndsLabel: "Scade",
        eligibleRequirementsLabel: "Requisiti",
        eligibleResultLabel: "Risultato",
        eligibleCoinsUnit: "crediti",
        eligibleTokensUnit: "gettoni",
        eligibleCostOr: "O",
        eligibleCompatibleLabel: "compatibili",
        eligibleFilterAll: "Tutte",
        eligibleFilterFree: "Gratis",
        eligibleFilterPaid: "A pagamento",
        eligibleSearchPlaceholder: "Cerca evoluzione...",
        eligibleSortLabel: "Ordina",
        eligibleSortBest: "Miglior risultato",
        eligibleSortOvr: "OVR finale",
        eligibleSortExpiry: "Scadenza",
        eligibleSortCost: "Costo",
        eligibleShowingPrefix: "Mostrate",
        eligibleShowingOf: "di",
        eligibleShowingSuffix: "evoluzioni",
        eligibleShowMore: "Mostra altre 3",
        eligibleShowAll: "Mostra tutte",
        eligibleNoMatches: "Nessuna evoluzione corrisponde a questi filtri.",
        eligibleViewDetails: "Vedi dettagli",
        eligibleHideDetails: "Nascondi dettagli",
      },
    },
    loading: "Caricamento di FUT Forge",
  },
} as const;

export type Dictionary = (typeof copy)[Locale];
