export const locales = ["en", "it"] as const;
export type Locale = (typeof locales)[number];

export const PRODUCT = {
  name: "FUT Forge",
  desktopName: "FUT Forge Desktop",
  version: "2.10.0",
  displayVersion: "2.10",
  email: "hello@futforge.app",
  wordmark: ["FUT", "FORGE"],
} as const;

export const siteCopy = {
  title: "FUT Forge — The desktop workspace for Ultimate Team",
  description: "Plan SBCs and Evolutions in one focused desktop application. Fewer tabs. Better decisions.",
  applicationName: "FUT Forge Desktop",
  category: "gaming",
  url: "https://futforge.vercel.app",
} as const;

export const copy = {
  en: {
    localeName: "English",
    languageShort: "EN",
    nav: {
      aria: "Main navigation",
      home: "FUT Forge home",
      desktop: "Desktop",
      features: "Features",
      roadmap: "Roadmap",
      download: "Download",
      cta: "Get FUT Forge",
      open: "Open navigation",
      close: "Close navigation",
      language: "Change language",
    },
    hero: {
      release: "FUT Forge Desktop 2.10",
      releaseNote: "A desktop workspace for Ultimate Team",
      words: ["BUILD", "OPTIMIZE", "DOMINATE"],
      lead: "Your Ultimate Team workspace. On desktop.",
      body: "Plan SBCs and Evolutions in one focused application. Fewer tabs. Better decisions.",
      primary: "Get FUT Forge",
      primaryMeta: "Windows 10 & 11",
      free: "Free",
      secondary: "Explore the workspace",
      secondaryMeta: "See real product screens",
      trust: ["Native Windows application", "Built for desktop", "Community-led"],
      proof: [
        ["12K+", "player profiles"],
        ["35", "advanced attributes"],
        ["Live", "SBC catalogue"],
        ["< 50ms", "local response"],
      ],
    },
    boot: {
      aria: "FUT Forge Desktop launch sequence",
      version: "FUT Forge Desktop 2.10",
      tagline: "Build. Optimize. Dominate.",
      ready: "Workspace ready",
      steps: [
        "Initializing workspace...",
        "Loading chemistry engine...",
        "Loading SBC Solver...",
        "Loading Squad Builder...",
        "Loading Evolution Engine...",
        "Synchronizing club...",
        "Ready.",
      ],
      secure: "Secure startup",
    },
    features: {
      label: "Inside the workspace",
      title: "Two focused workflows.",
      titleMuted: "One desktop workspace.",
      intro: "Real captures from the current FUT Forge application. Purpose-built for Ultimate Team, without the browser clutter.",
      stories: [
        {
          eyebrow: "SBC Solver",
          title: "Solve the challenge. Keep the value.",
          text: "Read every requirement, shape the solution, and stay focused from the first squad to submission.",
          alt: "FUT Forge SBC Solver desktop workspace",
          points: ["Live challenge catalogue", "Requirements at a glance", "A focused desktop workflow"],
        },
        {
          eyebrow: "EVO Builder",
          title: "Plan the player before the grind.",
          text: "Compare Evolution routes, understand each outcome, and commit only when the path is right.",
          alt: "FUT Forge EVO Builder desktop workspace",
          points: ["Player-first planning", "Clear route comparison", "Saved Evolution paths"],
        },
      ],
    },
    frame: {
      desktop: "Desktop",
      captured: "Captured in FUT Forge 2.10",
      platform: "Windows desktop application",
      aria: "Current FUT Forge product capture",
    },
    download: {
      label: "FUT Forge Desktop",
      title: "Your workspace is ready.",
      body: "One application for the Ultimate Team decisions that matter. Free to download. Built for Windows.",
      button: "Download for Windows",
      unavailable: "Download coming soon",
      platform: "Windows 10/11 · 64-bit",
      updates: "Automatic updates",
      version: "Version",
      filename: "Installer",
      released: "Released",
      latest: "Latest release",
    },
    roadmap: {
      label: "Product roadmap",
      title: "Built in public.",
      titleMuted: "Scoped with care.",
      body: "Shipping work is shown as shipped. Future milestones appear only after their scope is confirmed.",
      steps: [
        { phase: "Now", title: "SBC Solver and EVO Builder", text: "The current desktop workspace, available in FUT Forge 2.10." },
        { phase: "Next", title: "Next milestone", text: "Scope will be published when development is confirmed." },
        { phase: "Later", title: "Long-term direction", text: "Reserved for product plans validated with the community." },
      ],
    },
    footer: {
      tagline: "A desktop workspace for Ultimate Team.",
      features: "Features",
      roadmap: "Roadmap",
      download: "Download",
      contact: "Contact",
      rights: "© 2026 FUT Forge. All rights reserved.",
      disclaimer: "Not affiliated with EA Sports or Electronic Arts.",
    },
    loading: "Loading FUT Forge",
  },
  it: {
    localeName: "Italiano",
    languageShort: "IT",
    nav: {
      aria: "Navigazione principale",
      home: "Torna all’inizio",
      desktop: "Desktop",
      features: "Funzionalità",
      roadmap: "Roadmap",
      download: "Download",
      cta: "Scarica FUT Forge",
      open: "Apri il menu",
      close: "Chiudi il menu",
      language: "Cambia lingua",
    },
    hero: {
      release: "FUT Forge Desktop 2.10",
      releaseNote: "Il workspace per Ultimate Team. Su desktop.",
      words: ["CREA", "OTTIMIZZA", "DOMINA"],
      lead: "Tutto Ultimate Team. In un’unica applicazione desktop.",
      body: "SBC ed Evoluzioni, in un solo workspace. Meno schede. Più controllo.",
      primary: "Scarica FUT Forge",
      primaryMeta: "Windows 10 e 11",
      free: "Gratis",
      secondary: "Guarda FUT Forge in azione",
      secondaryMeta: "Esplora i workflow",
      trust: ["Applicazione desktop per Windows", "Workflow dedicati", "Sviluppata con la community"],
      proof: [
        ["12K+", "profili dei giocatori"],
        ["35", "attributi avanzati"],
        ["Sempre", "catalogo SBC"],
        ["< 50 ms", "risposta locale"],
      ],
    },
    boot: {
      aria: "Avvio di FUT Forge Desktop",
      version: "FUT Forge Desktop 2.10",
      tagline: "Crea. Ottimizza. Domina.",
      ready: "Workspace pronto",
      steps: [
        "Preparazione del workspace...",
        "Caricamento del motore dell’Intesa...",
        "Caricamento di SBC Solver...",
        "Caricamento di Squad Builder...",
        "Caricamento del motore Evoluzioni...",
        "Sincronizzazione del club...",
        "Pronto.",
      ],
      secure: "Avvio protetto",
    },
    features: {
      label: "Dentro il workspace",
      title: "Due workflow essenziali.",
      titleMuted: "Un solo workspace.",
      intro: "Screenshot reali dell’applicazione. SBC ed Evoluzioni, senza il caos del browser.",
      stories: [
        {
          eyebrow: "SBC Solver",
          title: "Completa la sfida. Proteggi il valore.",
          text: "Requisiti chiari, soluzione sotto controllo. Dalla prima rosa all’invio.",
          alt: "SBC Solver nel workspace desktop di FUT Forge",
          points: ["Catalogo SBC sempre aggiornato", "Requisiti chiari a colpo d’occhio", "Workflow senza distrazioni"],
        },
        {
          eyebrow: "EVO Builder",
          title: "Progetta il giocatore prima di iniziare.",
          text: "Confronta ogni percorso, valuta il risultato e scegli con chiarezza prima di iniziare.",
          alt: "EVO Builder nel workspace desktop di FUT Forge",
          points: ["Pianificazione centrata sul giocatore", "Confronto chiaro dei percorsi", "Evoluzioni salvate nel workspace"],
        },
      ],
    },
    frame: {
      desktop: "Desktop",
      captured: "Screenshot da FUT Forge 2.10",
      platform: "Applicazione desktop per Windows",
      aria: "Screenshot dell’applicazione FUT Forge",
    },
    download: {
      label: "FUT Forge Desktop",
      title: "Il tuo workspace è pronto.",
      body: "SBC ed Evoluzioni in un solo workspace. Gratis. Per Windows.",
      button: "Scarica per Windows",
      unavailable: "Download in arrivo",
      platform: "Windows 10/11 · 64 bit",
      updates: "Aggiornamenti automatici",
      version: "Versione",
      filename: "Installer",
      released: "Pubblicata il",
      latest: "Ultima versione",
    },
    roadmap: {
      label: "Roadmap",
      title: "Disponibile ora.",
      titleMuted: "Il resto, quando è pronto.",
      body: "Mostriamo ciò che esiste. Le prossime tappe entrano nella roadmap solo a sviluppo confermato.",
      steps: [
        { phase: "Ora", title: "SBC Solver ed EVO Builder", text: "Disponibili ora nel workspace FUT Forge 2.10." },
        { phase: "Prossimamente", title: "Prossimo aggiornamento", text: "Pubblicheremo i dettagli quando lo sviluppo sarà confermato." },
        { phase: "Più avanti", title: "Direzione futura", text: "Idee da valutare con la community prima di aggiungerle alla roadmap." },
      ],
    },
    footer: {
      tagline: "Il workspace per Ultimate Team. Su desktop.",
      features: "Funzionalità",
      roadmap: "Roadmap",
      download: "Download",
      contact: "Contatti",
      rights: "© 2026 FUT Forge. Tutti i diritti riservati.",
      disclaimer: "FUT Forge non è affiliato a EA Sports o Electronic Arts.",
    },
    loading: "Caricamento di FUT Forge",
  },
} as const;

export type Dictionary = (typeof copy)[Locale];
