import assert from "node:assert/strict";
import test from "node:test";
import { isLeakCategory, isLeakConfidence, isPublicLeak, normalizeIncomingReport, reportsMatch, safeHttpUrl } from "./core.ts";
const base = { sourceId: "source-1", sourceName: "Synthetic Source", title: " Player X - Thunderstruck ", category: "PLAYER", playerId: "player-x", eventKey: "Thunderstruck" };
test("normalization produces a stable, source-independent deduplication key", () => { const a = normalizeIncomingReport(base); const b = normalizeIncomingReport({ ...base, sourceId: "source-2", sourceName: "Another Source" }); assert.equal(a.normalizedSubject, "player x thunderstruck"); assert.equal(a.deduplicationKey, b.deduplicationKey); assert.equal(a.confidence, "RUMOR"); });
test("matching prioritizes player identifiers and event", () => { const a = normalizeIncomingReport(base); const b = normalizeIncomingReport({ ...base, title: "Completely different wording", sourceId: "source-2" }); const c = normalizeIncomingReport({ ...base, eventKey: "Winter Wildcards" }); assert.equal(reportsMatch(a,b), true); assert.equal(reportsMatch(a,c), false); });
test("validation rejects unsupported taxonomy values", () => { assert.equal(isLeakCategory("SBC"), true); assert.equal(isLeakCategory("TRANSFER"), false); assert.equal(isLeakConfidence("CONFIRMED"), true); assert.throws(() => normalizeIncomingReport({ ...base, category: "INVALID" }), /Invalid leak category/); });
test("public filtering requires a published flag and non-future publication", () => { assert.equal(isPublicLeak({ is_published: false, published_at: new Date(0).toISOString() }), false); assert.equal(isPublicLeak({ is_published: true, published_at: new Date(Date.now() - 1000).toISOString() }), true); assert.equal(isPublicLeak({ is_published: true, published_at: new Date(Date.now() + 60_000).toISOString() }), false); });
test("URL validation accepts only HTTP and HTTPS navigation targets", () => { assert.equal(safeHttpUrl("https://futforge.app/leaks/one"), "https://futforge.app/leaks/one"); assert.equal(safeHttpUrl("javascript:alert(1)"), null); assert.equal(safeHttpUrl("data:text/html,<script>alert(1)</script>"), null); assert.equal(safeHttpUrl("not a URL"), null); assert.throws(() => normalizeIncomingReport({ ...base, sourceUrl: "javascript:alert(1)" }), /Invalid source URL/); assert.throws(() => normalizeIncomingReport({ ...base, imageUrl: "data:image/svg+xml,bad" }), /Invalid image URL/); });
