import type { PlayerDetail } from "./players";
export const HIDDEN_GEM_SORTS=["score","overall","pace","shooting","passing","dribbling","defending","physical"] as const;
export type HiddenGemSort=(typeof HIDDEN_GEM_SORTS)[number];
export type HiddenGemQuery={maxOvr:number;position?:string;nation?:string;league?:string;club?:string;skillMovesMin?:number;weakFootMin?:number;sort:HiddenGemSort};
export type GemReason={label:string;value:number;kind:"delta"|"absolute"|"trait"};
export type HiddenGem={player:PlayerDetail;score:number;reasons:GemReason[];role:string;relative:number;quality:number};
export type HiddenGemResult={gems:HiddenGem[];candidateCount:number;elapsedMs:number};
type Face="pace"|"shooting"|"passing"|"dribbling"|"defending"|"physicality";type Metric={key:string;label:string;weight:number;face?:Face};const m=(key:string,label:string,weight:number,face?:Face):Metric=>({key,label,weight,face});
export const ROLE_METRICS:Record<string,Metric[]>={
striker:[m("pace","PAC",1.1,"pace"),m("shooting","SHO",1.35,"shooting"),m("dribbling","DRI",1,"dribbling"),m("physicality","PHY",.55,"physicality"),m("finishing","Finishing",1.2),m("positioning","Positioning",.8),m("reactions","Reactions",.75),m("composure","Composure",.65)],
winger:[m("pace","PAC",1.25,"pace"),m("dribbling","DRI",1.25,"dribbling"),m("passing","PAS",.7,"passing"),m("shooting","SHO",.65,"shooting"),m("acceleration","Acceleration",.8),m("sprint_speed","Sprint Speed",.7),m("agility","Agility",.7),m("ball_control","Ball Control",.65)],
midfielder:[m("passing","PAS",1.25,"passing"),m("dribbling","DRI",1.05,"dribbling"),m("reactions","Reactions",.8),m("vision","Vision",.85),m("short_passing","Short Passing",.85),m("stamina","Stamina",.7)],
defensiveMid:[m("defending","DEF",1.2,"defending"),m("physicality","PHY",1.05,"physicality"),m("passing","PAS",.75,"passing"),m("interceptions","Interceptions",.95),m("reactions","Reactions",.65),m("stamina","Stamina",.8)],
centerBack:[m("defending","DEF",1.35,"defending"),m("physicality","PHY",1.05,"physicality"),m("pace","PAC",.65,"pace"),m("interceptions","Interceptions",.9),m("defensive_awareness","Def. Awareness",.95),m("strength","Strength",.8),m("reactions","Reactions",.6)],
fullback:[m("pace","PAC",1.15,"pace"),m("defending","DEF",1.1,"defending"),m("physicality","PHY",.75,"physicality"),m("passing","PAS",.7,"passing"),m("stamina","Stamina",.9)],
goalkeeper:[m("pace","DIV",1.05,"pace"),m("shooting","HAN",1.05,"shooting"),m("dribbling","REF",1.25,"dribbling"),m("physicality","POS",1.05,"physicality")]};
export function gemRole(p:string){if(p==="GK")return"goalkeeper";if(p==="CB")return"centerBack";if(["LB","RB","LWB","RWB"].includes(p))return"fullback";if(p==="CDM")return"defensiveMid";if(["CM","CAM"].includes(p))return"midfielder";if(["LW","RW","LM","RM"].includes(p))return"winger";return"striker";}
const ROLE_ADJUSTMENT:Record<string,number>={winger:-10,striker:5,midfielder:3,defensiveMid:8,centerBack:9,fullback:6,goalkeeper:8};
function value(p:PlayerDetail,x:Metric){return x.face?p[x.face]:p.detailed_attributes?.[x.key]?.value??null;}
export function scoreHiddenGem(player:PlayerDetail):HiddenGem|null{const role=gemRole(player.position_short_label),metrics=ROLE_METRICS[role];let weight=0,rs=0,qs=0;const values=metrics.flatMap(metric=>{const v=value(player,metric);if(v==null)return[];weight+=metric.weight;rs+=Math.max(0,v-player.overall)*metric.weight;qs+=Math.max(0,v-75)*metric.weight;return[{metric,value:v,delta:v-player.overall}]});if(!weight)return null;const relative=rs/weight,quality=qs/weight,avg=values.reduce((s,x)=>s+x.value*x.metric.weight,0)/weight;if(player.overall<70||values.filter(x=>x.value>=82).length<2||avg<80)return null;const skills=Math.min(player.skill_moves_raw,5),weak=Math.min(player.weak_foot,5),bonus=(skills===4?1:skills>=5?2:0)+(weak===4?.75:weak>=5?1.5:0),score=Math.min(99,Math.round(35+relative+quality*3+bonus+ROLE_ADJUSTMENT[role]));const reasons:GemReason[]=values.filter(x=>x.delta>0).sort((a,b)=>b.delta-a.delta||b.value-a.value).slice(0,2).map(x=>({label:x.metric.label,value:x.delta,kind:"delta"}));const used=new Set(reasons.map(x=>x.label)),absolute=values.filter(x=>!used.has(x.metric.label)&&x.value>=85).sort((a,b)=>b.value-a.value)[0];if(absolute)reasons.push({label:absolute.metric.label,value:absolute.value,kind:"absolute"});if(reasons.length<3&&skills>=4)reasons.push({label:"Skills",value:skills,kind:"trait"});else if(reasons.length<3&&weak>=4)reasons.push({label:"Weak Foot",value:weak,kind:"trait"});return{player,score,reasons:reasons.slice(0,3),role,relative:+relative.toFixed(2),quality:+quality.toFixed(2)};}
