import "server-only";
import { HIDDEN_GEM_SORTS, scoreHiddenGem, type HiddenGemQuery, type HiddenGemResult, type HiddenGemSort } from "./hidden-gems-shared";
import { getAllPlayersStatic, isFc27ArtifactError } from "./static-data";
import { boundedFc27SupabaseFetch } from "./supabase-fallback";
import { DETAIL_COLUMNS, type PlayerDetail } from "./players";
export function isHiddenGemSort(value:string|undefined):value is HiddenGemSort{return !!value&&HIDDEN_GEM_SORTS.includes(value as HiddenGemSort)}
export async function fetchHiddenGems(query:HiddenGemQuery):Promise<HiddenGemResult>{
 const started=performance.now();let candidates:PlayerDetail[];
 try{candidates=(await getAllPlayersStatic()).filter(p=>p.overall>=70&&p.overall<=query.maxOvr&&(!query.position||p.position_short_label===query.position)&&(!query.nation||p.nationality_name===query.nation)&&(!query.league||p.league_name===query.league)&&(!query.club||(p.club_name??"").toLowerCase().includes(query.club.toLowerCase()))&&(!query.skillMovesMin||p.skill_moves_raw>=query.skillMovesMin)&&(!query.weakFootMin||p.weak_foot>=query.weakFootMin))}
 catch(error){if(!isFc27ArtifactError(error))throw error;console.warn(`[FC27 DATA] static artifact unavailable: hidden-gems (${error.artifact})`);const url=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://axjuxmjoowrzmvyhbdhv.supabase.co",key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"sb_publishable_bMremihmEy34CWp5rG6M-g_UuysymCX",params=new URLSearchParams({select:DETAIL_COLUMNS,overall:"gte.70",limit:"1000"});params.append("overall",`lte.${query.maxOvr}`);const response=await boundedFc27SupabaseFetch("hidden-gems",`${url}/rest/v1/fc27_players?${params}`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!response.ok)throw new Error(`Unable to load hidden gems (${response.status})`);candidates=await response.json() as PlayerDetail[]}
 candidates=candidates.filter(p=>(!query.position||p.position_short_label===query.position)&&(!query.nation||p.nationality_name===query.nation)&&(!query.league||p.league_name===query.league)&&(!query.club||(p.club_name??"").toLowerCase().includes(query.club.toLowerCase()))&&(!query.skillMovesMin||p.skill_moves_raw>=query.skillMovesMin)&&(!query.weakFootMin||p.weak_foot>=query.weakFootMin));
 const gems=candidates.flatMap(player=>{const gem=scoreHiddenGem(player);return gem?[gem]:[]});gems.sort((a,b)=>{if(query.sort==="score")return b.score-a.score||a.player.overall-b.player.overall||a.player.display_name.localeCompare(b.player.display_name)||a.player.ea_player_id-b.player.ea_player_id;const field=query.sort==="physical"?"physicality":query.sort,av=a.player[field]??-1,bv=b.player[field]??-1;return bv-av||b.score-a.score||a.player.display_name.localeCompare(b.player.display_name)||a.player.ea_player_id-b.player.ea_player_id});return{gems:gems.slice(0,50),candidateCount:candidates.length,elapsedMs:Math.round(performance.now()-started)}
}
