"use client";
import Link from "next/link";
import { useI18n } from "@/components/i18n-provider";
import { leaksCopy } from "@/lib/leaks/copy";
import type { Leak } from "@/lib/leaks/types";
import { localizeLeakContent } from "@/lib/leaks/localize";

export function LeakDetail({ leak }: { leak: Leak }) {
  const { locale } = useI18n(); const t = leaksCopy[locale]; const localized = localizeLeakContent(leak, locale); const date = (value: string) => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
  return <article className="mx-auto max-w-6xl"><Link href="/app/leaks" className="font-mono text-[9px] uppercase tracking-[.16em] text-lime">← {t.back}</Link>
    <div className="mt-7 grid overflow-hidden rounded-[30px] border border-white/10 bg-white/[.025] lg:grid-cols-[1.1fr_.9fr]">
      <div className="relative min-h-[340px] overflow-hidden bg-[radial-gradient(circle_at_50%_30%,rgba(200,255,61,.14),transparent_35%),linear-gradient(145deg,#111512,#070908)] lg:min-h-[560px]">{leak.imageUrl && <div className="absolute inset-0 bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url(${JSON.stringify(leak.imageUrl).slice(1,-1)})` }}/>}<div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent"/></div>
      <div className="flex flex-col justify-center p-7 sm:p-10 lg:p-12"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-lime/25 bg-lime/5 px-3 py-1.5 font-mono text-[8px] uppercase tracking-widest text-lime">{t.categories[leak.category]}</span><span className="rounded-full border border-white/15 px-3 py-1.5 font-mono text-[8px] uppercase tracking-widest text-white/70">{t.statuses[leak.confidence]}</span></div><h1 className="mt-6 text-4xl font-bold tracking-[-.055em] sm:text-5xl">{localized.title}</h1><p className="mt-5 text-base leading-7 text-white/55">{localized.shortDescription}</p><dl className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10"><div className="bg-[#0b0e0c] p-4"><dt className="font-mono text-[8px] uppercase tracking-widest text-white/35">{t.firstSeen}</dt><dd className="mt-2 text-xs text-white/75">{date(leak.firstSeenAt)}</dd></div><div className="bg-[#0b0e0c] p-4"><dt className="font-mono text-[8px] uppercase tracking-widest text-white/35">{t.published}</dt><dd className="mt-2 text-xs text-white/75">{date(leak.publishedAt)}</dd></div></dl></div>
    </div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><section className="rounded-[26px] border border-white/10 bg-white/[.02] p-7 sm:p-9"><p className="whitespace-pre-wrap text-[15px] leading-8 text-white/65">{localized.content}</p>{leak.player && <div className="mt-9 border-t border-white/10 pt-7"><h2 className="font-mono text-[9px] uppercase tracking-[.18em] text-lime">{t.playerDetails}</h2><div className="mt-4 flex flex-wrap gap-3 text-sm text-white/65">{leak.player.name && <span>{leak.player.name}</span>}{leak.player.rating && <span>· {leak.player.rating} OVR</span>}{leak.player.position && <span>· {leak.player.position}</span>}{leak.player.rarity && <span>· {leak.player.rarity}</span>}</div></div>}</section>
      <aside><h2 className="font-mono text-[9px] uppercase tracking-[.18em] text-white/45">{t.sources}</h2><div className="mt-4 space-y-3">{leak.reports.map(report => <a key={report.id} href={report.sourceUrl || report.source.url || undefined} target="_blank" rel="noreferrer" className="block rounded-2xl border border-white/10 bg-white/[.025] p-5 transition hover:border-lime/20"><div className="flex items-center justify-between"><strong className="text-sm">{report.source.name}</strong><span className="font-mono text-[8px] uppercase tracking-wider text-white/35">{report.source.platform}</span></div>{report.excerpt && <p className="mt-3 text-xs leading-5 text-white/45">{report.excerpt}</p>}<p className="mt-3 font-mono text-[8px] uppercase tracking-wider text-lime/70">{date(report.reportedAt)} ↗</p></a>)}</div></aside>
    </div>
  </article>;
}
