"use client";
import Link from "next/link";
import { useI18n } from "@/components/i18n-provider";
import { leaksCopy } from "@/lib/leaks/copy";
import type { Leak } from "@/lib/leaks/types";
import { localizeLeakContent } from "@/lib/leaks/localize";

export function LeakDetail({ leak }: { leak: Leak }) {
  const { locale } = useI18n(); const t = leaksCopy[locale]; const localized = localizeLeakContent(leak, locale); const date = (value: string) => new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
  const label = (handle: string | null, fallback: string) => handle && handle in t.sourceLabels ? t.sourceLabels[handle as keyof typeof t.sourceLabels] : fallback;
  return <article className="mx-auto max-w-6xl"><Link href="/app/leaks" className="font-mono text-[9px] uppercase tracking-[.16em] text-lime">← {t.back}</Link>
    <div className="mt-7 grid overflow-hidden rounded-[30px] border border-white/10 bg-white/[.025] lg:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[340px] overflow-hidden bg-black/30 lg:min-h-[560px]">{leak.imageUrl && <div className="absolute inset-0 bg-contain bg-center bg-no-repeat" style={{ backgroundImage: `url(${JSON.stringify(leak.imageUrl).slice(1,-1)})` }}/>}</div><div className="flex flex-col justify-center p-7 sm:p-10 lg:p-12"><div className="flex flex-wrap gap-2"><span className="rounded-full border border-lime/25 bg-lime/5 px-3 py-1.5 font-mono text-[8px] uppercase text-lime">{t.categories[leak.category]}</span><span className="rounded-full border border-white/15 px-3 py-1.5 font-mono text-[8px] uppercase text-white/70">{leak.game} · {t.leakStatuses[leak.status]}</span></div><h1 className="mt-6 text-4xl font-bold sm:text-5xl">{localized.title}</h1><p className="mt-5 text-base leading-7 text-white/55">{localized.shortDescription}</p><dl className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10"><div className="bg-[#0b0e0c] p-4"><dt className="font-mono text-[8px] uppercase text-white/35">{t.firstSeen}</dt><dd className="mt-2 text-xs text-white/75">{date(leak.firstSeenAt)}</dd></div><div className="bg-[#0b0e0c] p-4"><dt className="font-mono text-[8px] uppercase text-white/35">{t.published}</dt><dd className="mt-2 text-xs text-white/75">{date(leak.publishedAt)}</dd></div></dl></div></div>
    <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_340px]"><section className="rounded-[26px] border border-white/10 bg-white/[.02] p-7 sm:p-9"><p className="whitespace-pre-wrap text-[15px] leading-8 text-white/65">{localized.content}</p></section><aside><h2 className="font-mono text-[9px] uppercase tracking-[.18em] text-white/45">{t.sources}</h2><div className="mt-4 space-y-3">{leak.reports.map(report => { const href = report.sourceUrl || report.source.url; const content = <><div className="flex items-center justify-between"><strong className="text-sm">{label(report.source.handle, report.source.name)}</strong><span className="font-mono text-[8px] uppercase text-white/35">{report.source.platform}</span></div>{report.excerpt && <p className="mt-3 text-xs leading-5 text-white/45">{report.excerpt}</p>}<p className="mt-3 font-mono text-[8px] uppercase text-lime/70">{date(report.reportedAt)}{href ? " ↗" : ""}</p></>; const classes = "block rounded-2xl border border-white/10 bg-white/[.025] p-5"; return href ? <a key={report.id} href={href} target="_blank" rel="noreferrer" className={`${classes} transition hover:border-lime/20`}>{content}</a> : <div key={report.id} className={classes}>{content}</div>; })}</div></aside></div>
  </article>;
}
