"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useI18n } from "@/components/i18n-provider";
import { leaksCopy } from "@/lib/leaks/copy";
import { LEAK_CATEGORIES, LEAK_CONFIDENCES, type Leak, type LeakCategory, type LeakConfidence } from "@/lib/leaks/types";
import { localizeLeakContent } from "@/lib/leaks/localize";

const confidenceStyle = { RUMOR: "border-white/15 text-white/55", LIKELY: "border-amber-300/25 bg-amber-300/5 text-amber-200", CONFIRMED: "border-lime/30 bg-lime/5 text-lime" } as const;
const formatDate = (value: string, locale: string) => new Intl.DateTimeFormat(locale, { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));

function FeedSkeleton() { return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3" aria-hidden>{[0,1,2,3,4,5].map((item) => <div key={item} className="h-[390px] animate-pulse rounded-[26px] border border-white/8 bg-white/[.025]"><div className="h-48 bg-white/[.035]" /><div className="space-y-4 p-6"><div className="h-3 w-24 rounded bg-white/10"/><div className="h-6 w-4/5 rounded bg-white/10"/><div className="h-3 w-full rounded bg-white/5"/><div className="h-3 w-2/3 rounded bg-white/5"/></div></div>)}</div>; }

export function LeaksFeed() {
  const { locale } = useI18n(); const t = leaksCopy[locale];
  const [leaks, setLeaks] = useState<Leak[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  const [category, setCategory] = useState<LeakCategory | "ALL">("ALL"); const [confidence, setConfidence] = useState<LeakConfidence | "ALL">("ALL"); const [order, setOrder] = useState<"newest"|"oldest">("newest"); const [search, setSearch] = useState(""); const [reload, setReload] = useState(0);
  useEffect(() => { const controller = new AbortController(); const params = new URLSearchParams({ order }); if (category !== "ALL") params.set("category", category); if (confidence !== "ALL") params.set("confidence", confidence); if (search.trim()) params.set("search", search.trim()); const timer = setTimeout(async () => { setLoading(true); setFailed(false); try { const response = await fetch(`/api/leaks?${params}`, { signal: controller.signal }); if (!response.ok) throw new Error(); const body = await response.json() as { leaks: Leak[] }; setLeaks(body.leaks); } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setFailed(true); } finally { if (!controller.signal.aborted) setLoading(false); } }, search ? 250 : 0); return () => { clearTimeout(timer); controller.abort(); }; }, [category, confidence, order, search, reload]);
  const filtered = useMemo(() => leaks, [leaks]); const hasFilters = category !== "ALL" || confidence !== "ALL" || !!search.trim();
  return <section><header className="mb-10 border-b border-white/10 pb-10"><p className="font-mono text-[9px] uppercase tracking-[.22em] text-lime">{t.eyebrow}</p><h1 className="mt-4 text-5xl font-bold tracking-[-.07em] sm:text-7xl">{t.title}<span className="text-lime">.</span></h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/50">{t.subtitle}</p></header>
    <div className="mb-8 flex gap-2 overflow-x-auto pb-2" aria-label={t.categories.PLAYER}>{(["ALL", ...LEAK_CATEGORIES.filter(c => c !== "OTHER")] as const).map(item => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full border px-4 py-2 font-mono text-[10px] uppercase tracking-[.12em] transition ${category === item ? "border-lime/40 bg-lime/10 text-lime" : "border-white/10 text-white/50 hover:border-white/20 hover:text-white"}`}>{item === "ALL" ? t.all : t.categories[item]}</button>)}</div>
    <div className="mb-8 grid gap-3 rounded-2xl border border-white/10 bg-white/[.025] p-3 md:grid-cols-[1fr_auto_auto]">
      <label className="flex min-h-12 items-center gap-3 rounded-xl border border-white/10 bg-black/20 px-4"><span className="text-white/35">⌕</span><span className="sr-only">{t.search}</span><input value={search} onChange={e => setSearch(e.target.value)} placeholder={t.searchPlaceholder} className="w-full bg-transparent text-sm outline-none placeholder:text-white/30" /></label>
      <label className="flex items-center gap-3 rounded-xl border border-white/10 px-4"><span className="font-mono text-[8px] uppercase tracking-widest text-white/35">{t.confidence}</span><select value={confidence} onChange={e => setConfidence(e.target.value as LeakConfidence|"ALL")} className="select-dark bg-transparent py-3 text-xs outline-none"><option value="ALL">{t.anyConfidence}</option>{LEAK_CONFIDENCES.map(item => <option key={item} value={item}>{t.statuses[item]}</option>)}</select></label>
      <label className="flex items-center gap-3 rounded-xl border border-white/10 px-4"><span className="font-mono text-[8px] uppercase tracking-widest text-white/35">{t.order}</span><select value={order} onChange={e => setOrder(e.target.value as "newest"|"oldest")} className="select-dark bg-transparent py-3 text-xs outline-none"><option value="newest">{t.newest}</option><option value="oldest">{t.oldest}</option></select></label>
    </div>
    {loading ? <FeedSkeleton /> : failed ? <State title={t.errorTitle} body={t.errorBody}><button onClick={() => setReload(v => v + 1)} className="mt-5 rounded-xl bg-lime px-5 py-3 text-xs font-bold text-black">{t.retry}</button></State> : filtered.length === 0 ? <State title={hasFilters ? t.noResultsTitle : t.emptyTitle} body={hasFilters ? t.noResultsBody : t.emptyBody} /> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(leak => { const localized = localizeLeakContent(leak, locale); return <article key={leak.id} className="group overflow-hidden rounded-[26px] border border-white/10 bg-white/[.025] transition hover:-translate-y-1 hover:border-lime/20 hover:shadow-2xl hover:shadow-black/30">
      <div className="relative flex h-48 items-end overflow-hidden bg-[radial-gradient(circle_at_70%_20%,rgba(200,255,61,.13),transparent_35%),linear-gradient(135deg,#111512,#080a09)]">{leak.imageUrl && <div className="absolute inset-0 bg-cover bg-center transition duration-700 group-hover:scale-105" style={{ backgroundImage: `url(${JSON.stringify(leak.imageUrl).slice(1,-1)})` }} />}<div className="absolute inset-0 bg-gradient-to-t from-[#090b0a] via-transparent to-transparent"/><div className="relative flex w-full items-center justify-between p-5"><span className="rounded-full border border-lime/25 bg-black/50 px-3 py-1.5 font-mono text-[8px] uppercase tracking-widest text-lime backdrop-blur">{t.categories[leak.category]}</span><span className={`rounded-full border bg-black/50 px-3 py-1.5 font-mono text-[8px] uppercase tracking-widest backdrop-blur ${confidenceStyle[leak.confidence]}`}>{t.statuses[leak.confidence]}</span></div></div>
      <div className="p-6"><p className="font-mono text-[9px] uppercase tracking-[.16em] text-white/35">{leak.reports[0]?.source.name || "FUT Forge"} · {formatDate(leak.publishedAt, locale)}</p><h2 className="mt-3 text-xl font-semibold tracking-[-.03em]">{localized.title}</h2><p className="mt-3 line-clamp-3 min-h-[60px] text-sm leading-6 text-white/50">{localized.shortDescription}</p><Link href={`/app/leaks/${leak.slug}`} className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-lime">{t.details}<span aria-hidden>↗</span></Link></div>
    </article>; })}</div>}
  </section>;
}

function State({ title, body, children }: { title: string; body: string; children?: React.ReactNode }) { return <div className="rounded-[28px] border border-dashed border-white/15 bg-white/[.02] px-6 py-20 text-center"><div className="mx-auto mb-5 grid size-12 place-items-center rounded-full border border-lime/20 bg-lime/5 text-lime">◇</div><h2 className="text-xl font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/45">{body}</p>{children}</div>; }
