"use client";
import { useEffect, useState } from "react";
import { useI18n } from "@/components/i18n-provider";
import type { AutoSquadPlayer, AutoSquadPriority, AutoSquadResult } from "@/lib/fc27/auto-squad";
import { track } from "@/lib/analytics/client";

type Options={leagues:string[];nations:string[];clubs:string[];positions:string[]};
type Props={formationId:string;hasSquad:boolean;onApply:(slots:Record<string,AutoSquadPlayer>)=>void};
const copy={
 en:{open:"Auto Build",title:"Auto Build",filters:"Filters",budgetTab:"Meta + Budget",league:"League",nation:"Nation",club:"Club",any:"Any",minOvr:"Minimum OVR",maxOvr:"Maximum OVR",minMeta:"Minimum Base Meta",priority:"Priority",meta:"Meta",balanced:"Balanced",chemistry:"Chemistry",minChem:"Minimum chemistry",build:"Build Squad",regenerate:"Regenerate",building:"Building…",close:"Close",replace:"Replace your current squad?",noResult:"A valid squad cannot be built with the selected filters.",result:"Generated squad",ovr:"Average OVR",baseMeta:"Average Base Meta",leagues:"League composition",nations:"Nation composition",clubs:"Club composition",coming:"Coming soon",budget:"Budget",budgetTitle:"Best Squad by Budget",budgetCopy:"FC 27 market prices are not available yet.\n\nThe budget-based squad generator will become available once the in-game market goes live.",budgetCta:"Build Best Squad"},
 it:{open:"Genera squadra",title:"Genera squadra",filters:"Filtri",budgetTab:"Meta + Budget",league:"Campionato",nation:"Nazione",club:"Club",any:"Qualsiasi",minOvr:"OVR minimo",maxOvr:"OVR massimo",minMeta:"Meta Base minimo",priority:"Priorità",meta:"Meta",balanced:"Bilanciata",chemistry:"Chemistry",minChem:"Chemistry minima",build:"Genera squadra",regenerate:"Rigenera",building:"Generazione…",close:"Chiudi",replace:"Sostituire la squadra attuale?",noResult:"Non è possibile creare una squadra valida con i filtri selezionati.",result:"Squadra generata",ovr:"OVR Medio",baseMeta:"Meta Base Media",leagues:"Composizione campionati",nations:"Composizione nazioni",clubs:"Composizione club",coming:"Presto disponibile",budget:"Budget",budgetTitle:"Migliore squadra per budget",budgetCopy:"Prezzi FC 27 non ancora disponibili.\n\nLa generazione automatica della miglior squadra in base al budget sarà disponibile con l’apertura del mercato.",budgetCta:"Crea squadra migliore"}
} as const;
export function AutoBuildPanel({formationId,hasSquad,onApply}:Props){const{locale}=useI18n(),c=copy[locale];const[open,setOpen]=useState(false),[tab,setTab]=useState<"filters"|"budget">("filters"),[options,setOptions]=useState<Options|null>(null),[values,setValues]=useState({league:"",nation:"",club:"",overallMin:"",overallMax:"",metaMin:"",priority:"meta" as AutoSquadPriority,chemistryMin:""}),[loading,setLoading]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<AutoSquadResult|null>(null);
 useEffect(()=>{if(!open||options)return;const controller=new AbortController();fetch("/api/fc27/auto-squad",{signal:controller.signal}).then(r=>r.ok?r.json() as Promise<Options>:Promise.reject()).then(setOptions).catch(()=>{if(!controller.signal.aborted)setError(c.noResult)});return()=>controller.abort()},[open,options,c.noResult]);
 useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape)},[open]);
 const set=(key:keyof typeof values,value:string)=>setValues(current=>({...current,[key]:value}));
 async function build(){setLoading(true);setError("");track("auto_build_started",{priority:values.priority});try{const numeric=(value:string)=>value?Number(value):undefined,response=await fetch("/api/fc27/auto-squad",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({formation:formationId,...values,overallMin:numeric(values.overallMin),overallMax:numeric(values.overallMax),metaMin:numeric(values.metaMin),chemistryMin:numeric(values.chemistryMin)})});if(!response.ok){setError(c.noResult);return}const generated=await response.json() as AutoSquadResult;if(hasSquad&&!confirm(c.replace))return;onApply(generated.slots);setResult(generated);track("auto_build_completed",{priority:values.priority})}catch{setError(c.noResult)}finally{setLoading(false)}}
 const composition=(key:"league_name"|"nationality_name"|"club_name")=>result?[...new Set(Object.values(result.slots).map(player=>player[key]).filter((value):value is string=>Boolean(value)))].sort().join(", "):"";
 return <><button className="fc27-auto-build-trigger" onClick={()=>setOpen(true)}>{c.open}</button>{open&&<div className="fc27-auto-build-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="fc27-auto-build-panel" role="dialog" aria-modal="true" aria-labelledby="auto-build-title"><header><div><span>FC 27</span><h2 id="auto-build-title">{c.title}</h2></div><button aria-label={c.close} onClick={()=>setOpen(false)}>×</button></header><nav><button className={tab==="filters"?"active":""} onClick={()=>setTab("filters")}>{c.filters}</button><button className={tab==="budget"?"active":""} onClick={()=>setTab("budget")}>{c.budgetTab}</button></nav>{tab==="filters"?<div className="fc27-auto-build-content"><div className="fc27-auto-filter-grid"><Select label={c.league} value={values.league} onChange={v=>set("league",v)} options={options?.leagues??[]} any={c.any}/><Select label={c.nation} value={values.nation} onChange={v=>set("nation",v)} options={options?.nations??[]} any={c.any}/><Select label={c.club} value={values.club} onChange={v=>set("club",v)} options={options?.clubs??[]} any={c.any}/><NumberField label={c.minOvr} value={values.overallMin} onChange={v=>set("overallMin",v)} max={99}/><NumberField label={c.maxOvr} value={values.overallMax} onChange={v=>set("overallMax",v)} max={99}/><NumberField label={c.minMeta} value={values.metaMin} onChange={v=>set("metaMin",v)} max={100}/><Select label={c.priority} value={values.priority} onChange={v=>set("priority",v)} options={["meta","balanced","chemistry"]} labels={[c.meta,c.balanced,c.chemistry]}/><Select label={c.minChem} value={values.chemistryMin} onChange={v=>set("chemistryMin",v)} options={["20","25","30","33"]} labels={["20+","25+","30+","33"]} any={c.any}/></div>{error&&<p className="fc27-auto-error" role="alert">{error}</p>}{result&&<div className="fc27-auto-result"><b>{c.result}</b><span>{c.ovr}: {result.averageOverall.toFixed(1)}</span><span>{c.baseMeta}: {result.averageMeta.toFixed(1)}</span><span>{c.chemistry}: {result.chemistry} / 33</span><small>{c.leagues}: {composition("league_name")}</small><small>{c.nations}: {composition("nationality_name")}</small><small>{c.clubs}: {composition("club_name")}</small></div>}<button className="fc27-auto-primary" disabled={loading||!options} onClick={build}>{loading?c.building:result?c.regenerate:c.build}</button></div>:<div className="fc27-auto-build-content"><label className="fc27-auto-budget"><span>{c.budget}</span><input type="number" min="0" max="1000000000" step="1000" placeholder="100,000" disabled/></label><div className="fc27-auto-coming"><span>{c.coming}</span><h3>{c.budgetTitle}</h3><p>{c.budgetCopy}</p></div><button className="fc27-auto-primary" disabled>{c.budgetCta}</button></div>}</section></div>}</>}
function Select({label,value,onChange,options,labels,any}:{label:string;value:string;onChange:(value:string)=>void;options:string[];labels?:readonly string[];any?:string}){return <label><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}>{any&&<option value="">{any}</option>}{options.map((option,index)=><option value={option} key={option}>{labels?.[index]??option}</option>)}</select></label>}
function NumberField({label,value,onChange,max}:{label:string;value:string;onChange:(value:string)=>void;max:number}){return <label><span>{label}</span><input type="number" min="1" max={max} value={value} onChange={event=>onChange(event.target.value)}/></label>}
