"use client";

import Link from "next/link";
import { useI18n } from "@/components/i18n-provider";
import { PlayerPortrait } from "./player-portrait";
import { playerUrlSlug } from "@/lib/fc27/player-slug";
import type { RankingPlayer } from "@/lib/fc27/rankings-shared";

const words={en:{title:"Best EA FC 27 players",intro:"Ranked by overall rating. Inspect headline stats, open detailed profiles, or compare players.",top:"Top 50 by overall rating",view:"View Player",compare:"Compare",advanced:"Use Stat Finder for advanced filtering",positions:"Browse players by position",nations:"Players by Nation",clubs:"Players by Club",leagues:"Players by League",rankings:"Rankings"},it:{title:"Migliori giocatori EA FC 27",intro:"Classifica per valutazione generale. Consulta le statistiche, i profili dettagliati o confronta i giocatori.",top:"Top 50 per valutazione generale",view:"Vedi giocatore",compare:"Confronta",advanced:"Usa Stat Finder per filtri avanzati",positions:"Esplora i giocatori per posizione",nations:"Giocatori per Nazione",clubs:"Giocatori per Club",leagues:"Giocatori per Campionato",rankings:"Classifiche"}};

export function EntityDetailView({name,total,players,parentHref,parentLabel}:{name:string;total:number;players:RankingPlayer[];parentHref:string;parentLabel:string}){const{locale}=useI18n();const c=words[locale],top=players[0],count=total.toLocaleString(locale==="it"?"it-IT":"en-US");return <main className="fc27-stat-page hero-grid relative min-h-screen overflow-hidden px-4 pb-24 pt-36 sm:px-6 sm:pt-40"><div className="hero-noise"/><div className="hero-orb hero-orb-primary"/><div className="relative mx-auto max-w-6xl">
  <Link href={parentHref} className="fc27-back-link">← {locale==="it"?"Torna a":"Back to"} {parentLabel}</Link><p className="section-label mt-5">EA FC 27</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">{c.title}: {name}</h1><p className="mt-4 max-w-3xl text-white/55">{top?(locale==="it"?`${name} conta ${count} giocatori nel database EA FC 27. ${top.display_name} è il giocatore con la valutazione più alta a ${top.overall} OVR.`:`${name} has ${count} players in the EA FC 27 database. ${top.display_name} is the highest-rated player at ${top.overall} OVR.`):c.intro}</p><p className="mt-4 text-sm font-semibold text-lime">{count} {locale==="it"?"giocatori":"players"}</p>
  <section className="mt-8" aria-labelledby="entity-results"><div className="fc27-stat-results-head"><div><h2 id="entity-results">{c.top}</h2><p>{players.length} / {total.toLocaleString()}</p></div></div><ol className="fc27-stat-results">{players.map((p,index)=>{const labels=p.position_short_label==="GK"?["DIV","HAN","KIC","REF","SPD","POS"]:["PAC","SHO","PAS","DRI","DEF","PHY"];const stats=[p.pace,p.shooting,p.passing,p.dribbling,p.defending,p.physicality];const href=`/fc27/players/${playerUrlSlug(p.ea_player_id,p.slug)}`;return <li className="fc27-stat-row" key={p.ea_player_id}><span className="fc27-ranking-number">#{index+1}</span><div className="fc27-ranking-portrait"><PlayerPortrait src={p.avatar_url} alt={p.display_name} overall={p.overall}/></div><div className="fc27-ranking-player"><Link href={href}>{p.display_name}</Link><span>{p.club_name??"—"}<i aria-hidden>·</i>{p.nationality_name}{p.league_name?<><i aria-hidden>·</i>{p.league_name}</>:null}</span></div><span className="fc27-ranking-position">{p.position_short_label}</span><span className="fc27-ranking-ovr"><b>{p.overall}</b><small>OVR</small></span><div className="fc27-stat-six">{stats.map((value,i)=><span key={labels[i]}><b>{value??"—"}</b><small>{labels[i]}</small></span>)}</div><div className="fc27-ranking-actions"><Link className="!min-h-11" href={href}>{c.view}</Link><Link className="compare !min-h-11" href={`/fc27/compare?a=${p.ea_player_id}`}>{c.compare}</Link></div></li>})}</ol></section>
  <section className="mt-10 rounded-2xl border border-white/10 bg-white/[.03] p-6"><p className="text-white/60">{c.intro}</p><div className="mt-4 flex flex-wrap gap-3 text-sm"><Link href="/fc27/positions">{c.positions}</Link><Link href="/fc27/stat-finder">{c.advanced}</Link><Link href="/fc27/nations">{c.nations}</Link><Link href="/fc27/clubs">{c.clubs}</Link><Link href="/fc27/leagues">{c.leagues}</Link><Link href="/fc27/rankings">{c.rankings}</Link></div></section>
 </div></main>}
