"use client";
import Link from "next/link";
import { useI18n } from "@/components/i18n-provider";
import { PlayerPortrait } from "./player-portrait";
import { playerUrlSlug } from "@/lib/fc27/player-slug";
import { playerHrefWithReturn } from "@/lib/fc27/return-navigation";
import type { PlayerDetail } from "@/lib/fc27/players";
import type { SimilarResult } from "@/lib/fc27/similar-players";

const labels:Record<string,{en:string;it:string}>={pace:{en:"PAC",it:"VEL"},shooting:{en:"SHO",it:"TIR"},passing:{en:"PAS",it:"PAS"},dribbling:{en:"DRI",it:"DRI"},defending:{en:"DEF",it:"DIF"},physicality:{en:"PHY",it:"FIS"},finishing:{en:"Finishing",it:"Finalizzazione"},positioning:{en:"Positioning",it:"Posizionamento"},shot_power:{en:"Shot Power",it:"Potenza tiro"},strength:{en:"Strength",it:"Forza"},acceleration:{en:"Acceleration",it:"Accelerazione"},sprint_speed:{en:"Sprint Speed",it:"Velocità scatto"},ball_control:{en:"Ball Control",it:"Controllo palla"},vision:{en:"Vision",it:"Visione"},short_passing:{en:"Short Passing",it:"Passaggi corti"},long_passing:{en:"Long Passing",it:"Passaggi lunghi"},stamina:{en:"Stamina",it:"Resistenza"},crossing:{en:"Crossing",it:"Cross"},standing_tackle:{en:"Standing Tackle",it:"Contrasto in piedi"},interceptions:{en:"Interceptions",it:"Intercettazioni"},defensive_awareness:{en:"Def. Awareness",it:"Consapevolezza dif."},gk_diving:{en:"Diving",it:"Tuffo"},gk_handling:{en:"Handling",it:"Presa"},gk_kicking:{en:"Kicking",it:"Rinvio"},gk_reflexes:{en:"Reflexes",it:"Riflessi"},gk_speed:{en:"Speed",it:"Velocità"},gk_positioning:{en:"Positioning",it:"Posizionamento"}};
export function Fc27SimilarPlayersView({source,results}:{source:PlayerDetail;results:SimilarResult[]}){const{locale}=useI18n();const it=locale==="it";const playerHref=`/fc27/players/${playerUrlSlug(source.ea_player_id,source.slug)}`;const returnTo=`/fc27/similar/${playerUrlSlug(source.ea_player_id,source.slug)}`;return <div className="fc27-similar-page hero-grid relative px-4 pb-24 pt-36 sm:px-6 sm:pt-44"><div className="hero-noise"/><main className="relative mx-auto max-w-6xl"><Link href={playerHref} className="fc27-back-link">← {it?"Torna al giocatore":"Back to player"}</Link><p className="section-label mt-5">{it?"FC 27 · ANALISI PROFILO":"FC 27 · PROFILE ANALYSIS"}</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">{it?"Giocatori simili a":"Players similar to"} {source.display_name}</h1><p className="mt-3 max-w-3xl text-white/55">{it?"Confronto deterministico e specifico per ruolo basato sugli attributi reali del giocatore.":"A deterministic, position-aware comparison based on real player attributes."}</p><section className="fc27-similar-source" aria-label={it?"Giocatore di partenza":"Source player"}>
  <div className="fc27-similar-source-portrait"><PlayerPortrait src={source.avatar_url} alt="" overall={source.overall} fit="contain"/></div>
  <div className="fc27-similar-source-identity">
    <span className="fc27-similar-source-label">{it?"GIOCATORE DI PARTENZA":"SOURCE PLAYER"}</span>
    <h2>{source.display_name}</h2>
    <b>{source.overall} OVR <i aria-hidden>·</i> {source.position_short_label}</b>
    <span>{source.club_name??"—"} <i aria-hidden>·</i> {source.nationality_name}</span>
    <Link href={playerHref}>{it?"Vedi giocatore":"View Player"}</Link>
  </div>
  <div className="fc27-similar-source-stats">
    {(source.position_short_label==="GK"
      ? [["DIV",source.goalkeeping.gk_diving?.value],["HAN",source.goalkeeping.gk_handling?.value],["KIC",source.goalkeeping.gk_kicking?.value],["REF",source.goalkeeping.gk_reflexes?.value],["SPD",source.goalkeeping.gk_speed?.value??source.pace],["POS",source.goalkeeping.gk_positioning?.value]]
      : [["PAC",source.pace],["SHO",source.shooting],["PAS",source.passing],["DRI",source.dribbling],["DEF",source.defending],["PHY",source.physicality]]
    ).map(([label,value])=><div key={label}><b>{value??"—"}</b><span>{label}</span></div>)}
  </div>
</section><section aria-labelledby="similar-results"><div className="fc27-hidden-heading fc27-similar-heading"><div><h2 id="similar-results">{it?"Top 20 Giocatori Simili":"Top 20 Similar Players"}</h2><p>{it?"La percentuale combina forma del profilo, livello degli attributi e compatibilità del ruolo.":"The percentage blends profile shape, attribute level, and role compatibility."}</p></div></div><ol className="fc27-similar-results">{results.map((r,i)=>{const p=r.player;const detail=playerHrefWithReturn(`/fc27/players/${playerUrlSlug(p.ea_player_id,p.slug)}`,returnTo);return <li key={p.ea_player_id} className="fc27-similar-row"><span className="fc27-ranking-number">#{i+1}</span><PlayerPortrait src={p.avatar_url} alt="" overall={p.overall}/><div className="fc27-ranking-player"><Link href={detail}>{p.display_name}</Link><span>{p.club_name??"—"} · {p.nationality_name}</span></div><span className="fc27-ranking-position">{p.position_short_label}</span><span className="fc27-ranking-ovr"><b>{p.overall}</b><small>OVR</small></span><div className="fc27-similar-score"><b>{r.similarity}%</b><small>{it?"similarità":"similarity"}</small></div><div className="fc27-hidden-reasons">{r.reasons.map(x=><span key={x.key}>{labels[x.key]?.[it?"it":"en"]??x.key}: {x.source}/{x.candidate}</span>)}</div><div className="fc27-ranking-actions"><Link href={detail}>{it?"Vedi giocatore":"View Player"}</Link><Link className="compare" href={`/fc27/compare?a=${source.ea_player_id}&b=${p.ea_player_id}`}>{it?"Confronta":"Compare"}</Link></div></li>})}</ol></section></main></div>}
