"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {useI18n} from "@/components/i18n-provider";
import {Fc27BasePlayerCard} from "./fc27-base-player-card";
import {FORMATIONS,DEFAULT_FORMATION_ID,formationById,type FormationSlot} from "@/lib/fc27/formations";
import {calculateSquadChemistry,isPositionCompatible} from "@/lib/fc27/squad-chemistry";
import {AutoBuildPanel} from "./auto-build-panel";
import type {PlayerListItem} from "@/lib/fc27/players";
import {track} from "@/lib/analytics/client";
type SquadPlayer=PlayerListItem&{base_meta:number|null};type Slots=Record<string,SquadPlayer>;const STORAGE_KEY="futforge-fc27-squad";
const words={en:{eyebrow:"FC 27 · SQUAD TOOLS",title:"EA FC 27 Squad Builder",intro:"Build your EA FC 27 squad using the complete FUT Forge player database. Choose a formation, search players, calculate chemistry and create your starting XI.",formation:"Formation",share:"Share Squad",clear:"Clear Squad",players:"Players",ovr:"Average OVR",meta:"Average Base Meta",chem:"Chemistry",clubs:"Clubs",nations:"Nations",leagues:"Leagues",select:"Search Players",search:"Search by player name",all:"All Players",compatible:"Compatible",out:"Out of Position",replace:"Replace",remove:"Remove",view:"View Player",none:"No players found",duplicate:"This player is already in your squad.",formationConfirm:"Changing formation will clear your current squad.",clearConfirm:"Clear your current squad?",copied:"Squad link copied!",copyFail:"Unable to copy the squad link.",empty:"empty",close:"Close player selector",hint:"Choose a slot, then search the complete FC27 database."},it:{eyebrow:"FC 27 · STRUMENTI ROSA",title:"Squad Builder EA FC 27",intro:"Crea la tua squadra EA FC 27 utilizzando il database completo di FUT Forge. Scegli un modulo, cerca i giocatori, calcola la chemistry e costruisci il tuo undici titolare.",formation:"Modulo",share:"Condividi Rosa",clear:"Svuota Rosa",players:"Giocatori",ovr:"OVR Medio",meta:"Meta Base Media",chem:"Chemistry",clubs:"Club",nations:"Nazioni",leagues:"Campionati",select:"Cerca Giocatori",search:"Cerca per nome",all:"Tutti i giocatori",compatible:"Compatibile",out:"Fuori ruolo",replace:"Sostituisci",remove:"Rimuovi",view:"Vedi giocatore",none:"Nessun giocatore trovato",duplicate:"Questo giocatore è già presente nella rosa.",formationConfirm:"Cambiare modulo svuoterà la rosa attuale.",clearConfirm:"Svuotare la rosa attuale?",copied:"Link della rosa copiato!",copyFail:"Impossibile copiare il link della rosa.",empty:"vuoto",close:"Chiudi selettore giocatore",hint:"Scegli uno slot, poi cerca nell’intero database FC27."}} as const;
function validSaved(raw:unknown){if(!raw||typeof raw!=="object")return null;const x=raw as {formation?:unknown;slots?:unknown};if(typeof x.formation!=="string"||!FORMATIONS.some(f=>f.id===x.formation)||!x.slots||typeof x.slots!=="object")return null;const slots:Record<string,number>={};for(const[k,v]of Object.entries(x.slots as Record<string,unknown>))if(typeof v==="number"&&Number.isSafeInteger(v)&&v>0)slots[k]=v;return{formation:x.formation,slots}}
function parseUrl(){try{const p=new URLSearchParams(location.search),f=p.get("f"),raw=p.get("p");if(!f||!FORMATIONS.some(x=>x.id===f)||!raw)return null;const allowed=new Set(formationById(f).slots.map(s=>s.id)),slots:Record<string,number>={};for(const token of raw.split(",").slice(0,11)){const[k,v]=token.split(":"),id=Number(v);if(allowed.has(k)&&Number.isSafeInteger(id)&&id>0)slots[k]=id}return{formation:f,slots}}catch{return null}}
async function loadPlayers(ids:number[]){if(!ids.length)return[];const r=await fetch("/api/fc27/squad-players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ids})});if(!r.ok)throw new Error("load");return((await r.json()) as {results:SquadPlayer[]}).results}
function MiniCard({player}:{player:SquadPlayer}){return <><Fc27BasePlayerCard eaPlayerId={player.ea_player_id} overall={player.overall} position={player.position_short_label} playerName={player.display_name} commonName={player.common_name} avatarUrl={player.avatar_url} nationalityImageUrl={player.nationality_image_url} nationalityName={player.nationality_name} clubImageUrl={player.club_image_url} clubName={player.club_name} pace={player.pace} shooting={player.shooting} passing={player.passing} dribbling={player.dribbling} defending={player.defending} physicality={player.physicality} isGoalkeeper={player.position_short_label==="GK"} alternatePosition={player.alternate_positions[0]?.short_label??null} preferredFootCode={player.preferred_foot_code} skillMoves={player.skill_moves_raw} weakFoot={player.weak_foot} size="grid" className="fc27-squad-mini-card"/>{player.base_meta!=null&&<span className="fc27-slot-meta-number">{player.base_meta.toFixed(1)}</span>}</>}
export function Fc27SquadBuilderView(){const{locale}=useI18n(),c=words[locale];const[formationId,setFormationId]=useState(DEFAULT_FORMATION_ID),[slots,setSlots]=useState<Slots>({}),[selected,setSelected]=useState<FormationSlot|null>(null),[query,setQuery]=useState(""),[results,setResults]=useState<SquadPlayer[]>([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[ready,setReady]=useState(false);const dialogRef=useRef<HTMLDivElement>(null),formation=formationById(formationId);
 useEffect(()=>{track("squad_builder_open");if(parseUrl())track("share_squad_opened")},[]);
 useEffect(()=>{const state=parseUrl()??validSaved((()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)??"null")}catch{return null}})());Promise.resolve().then(async()=>{if(!state){setReady(true);return}setFormationId(state.formation);try{const rows=await loadPlayers(Object.values(state.slots)),byId=new Map(rows.map(p=>[p.ea_player_id,p])),next:Slots={};for(const[k,id]of Object.entries(state.slots)){const p=byId.get(id);if(p)next[k]=p}setSlots(next)}catch{setNotice(c.none)}finally{setReady(true)}})},[c.none]);
 useEffect(()=>{if(!ready)return;localStorage.setItem(STORAGE_KEY,JSON.stringify({formation:formationId,slots:Object.fromEntries(Object.entries(slots).map(([k,p])=>[k,p.ea_player_id]))}))},[formationId,slots,ready]);
 useEffect(()=>{if(!selected||query.trim().length<2)return;const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);try{const r=await fetch(`/api/fc27/squad-players?q=${encodeURIComponent(query.trim())}&position=${selected.position}`,{signal:controller.signal});setResults(r.ok?((await r.json()) as {results:SquadPlayer[]}).results:[])}catch{if(!controller.signal.aborted)setNotice(c.none)}finally{setLoading(false)}},250);return()=>{clearTimeout(timer);controller.abort()}},[query,selected,c.none]);
 useEffect(()=>{if(!selected)return;dialogRef.current?.querySelector<HTMLElement>("input,button")?.focus();const esc=(e:KeyboardEvent)=>{if(e.key==="Escape")setSelected(null)};document.addEventListener("keydown",esc);return()=>document.removeEventListener("keydown",esc)},[selected]);
 const rows=formation.slots.flatMap(slot=>slots[slot.id]?[{player:slots[slot.id],slot:slot.position}]:[]),chem=calculateSquadChemistry(rows),chemById=new Map(chem.players.map(x=>[x.playerId,x])),players=Object.values(slots),avgOvr=players.length?players.reduce((n,p)=>n+p.overall,0)/players.length:null,metaPlayers=players.filter(p=>p.base_meta!=null),avgMeta=metaPlayers.length?metaPlayers.reduce((n,p)=>n+(p.base_meta??0),0)/metaPlayers.length:null,unique=(key:"club_id"|"nationality_id"|"league_name")=>new Set(players.map(p=>p[key]).filter(x=>x!=null)).size;
 function choose(player:SquadPlayer){if(players.some(p=>p.ea_player_id===player.ea_player_id)){setNotice(c.duplicate);return}if(selected)setSlots(v=>({...v,[selected.id]:player}));setSelected(null);setQuery("");setResults([])}function changeFormation(id:string){if(players.length&&!confirm(c.formationConfirm))return;setFormationId(id);setSlots({})}
 async function share(){const state=formation.slots.filter(s=>slots[s.id]).map(s=>`${s.id}:${slots[s.id].ea_player_id}`).join(","),url=new URL(location.href);url.search="";url.searchParams.set("f",formationId);if(state)url.searchParams.set("p",state);try{await navigator.clipboard.writeText(url.toString());setNotice(c.copied);track("share_squad_created")}catch{setNotice(c.copyFail)}}
 return <main className="fc27-squad-page hero-grid relative min-h-screen px-3 pb-24 pt-32 sm:px-6 sm:pt-40"><div className="hero-noise"/><div className="relative mx-auto max-w-[1440px]"><p className="section-label">{c.eyebrow}</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">{c.title}</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/55 sm:text-base">{c.intro}</p><div className="fc27-squad-toolbar"><label><span>{c.formation}</span><select value={formationId} onChange={e=>changeFormation(e.target.value)}>{FORMATIONS.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><AutoBuildPanel formationId={formationId} hasSquad={players.length>0} onApply={generated=>{setSlots(generated as Slots);setNotice("")}}/><button onClick={share}>{c.share}</button><button className="danger" disabled={!players.length} onClick={()=>{if(confirm(c.clearConfirm))setSlots({})}}>{c.clear}</button></div>{notice&&<p className="fc27-squad-notice" role="status">{notice}</p>}
 <div className="fc27-squad-layout"><section className="fc27-squad-pitch" aria-label={`${formation.name} ${c.players}`}><div className="fc27-pitch-lines"><i/><b/><span/></div>{formation.slots.map(slot=>{const player=slots[slot.id],detail=player?chemById.get(player.ea_player_id):null;return <div className="fc27-squad-slot" key={slot.id} style={{left:`${slot.x}%`,top:`${slot.y}%`}}><button onClick={()=>{setSelected(slot);setQuery("");setResults([]);setNotice("")}} aria-label={player?`${slot.position}, ${player.display_name}, ${player.overall} overall, chemistry ${detail?.chemistry??0}`:`${slot.position} slot, ${c.empty}`} className={player?"occupied":"empty"}>{player?<MiniCard player={player}/>:<><b>{slot.position}</b><span>+</span></>}</button>{player&&<div className="fc27-slot-chem" data-oop={!detail?.inPosition}>{detail?.inPosition?`${"◆".repeat(detail.chemistry)}${"◇".repeat(3-detail.chemistry)}`:c.out}</div>}</div>})}</section><aside className="fc27-squad-summary"><h2>{c.players}: {players.length} / 11</h2><dl><div><dt>{c.formation}</dt><dd>{formation.name}</dd></div><div><dt>{c.ovr}</dt><dd>{avgOvr?.toFixed(1)??"—"}</dd></div><div><dt>{c.meta}</dt><dd>{avgMeta?.toFixed(1)??"—"}</dd></div><div className="primary"><dt>{c.chem}</dt><dd>{chem.total} / {chem.maximum}</dd></div><div><dt>{c.clubs}</dt><dd>{unique("club_id")}</dd></div><div><dt>{c.nations}</dt><dd>{unique("nationality_id")}</dd></div><div><dt>{c.leagues}</dt><dd>{unique("league_name")}</dd></div></dl><p>{c.hint}</p></aside></div>
 {selected&&<div className="fc27-player-selector-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="fc27-player-selector" role="dialog" aria-modal="true" aria-labelledby="squad-selector-title" ref={dialogRef}><header><div><span>{selected.position}</span><h2 id="squad-selector-title">{slots[selected.id]?c.replace:c.select}</h2></div><button onClick={()=>setSelected(null)} aria-label={c.close}>×</button></header><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={c.search} aria-label={c.search}/><p className="fc27-selector-filter">{c.compatible} · {c.all}</p><div className="fc27-selector-results">{loading?<p>…</p>:results.length?results.map(player=>{const compatible=isPositionCompatible(player,selected.position),used=players.some(p=>p.ea_player_id===player.ea_player_id);return <button key={player.ea_player_id} disabled={used} onClick={()=>choose(player)}><span className="portrait"><MiniCard player={player}/></span><span><b>{player.display_name}</b><small>{player.overall} OVR · {player.position_short_label}{player.alternate_positions.length?` / ${player.alternate_positions.map(p=>p.short_label).join(", ")}`:""}</small><small>{player.club_name??"—"} · {player.nationality_name} · {player.league_name??"—"}</small></span><em className={compatible?"compatible":"oop"}>{compatible?c.compatible:c.out}</em></button>}):query.length>=2?<p>{c.none}</p>:<p>{c.hint}</p>}</div>{slots[selected.id]&&<footer><button onClick={()=>{setSlots(v=>{const n={...v};delete n[selected.id];return n});setSelected(null)}}>{c.remove}</button><Link href={`/fc27/players/${slots[selected.id].ea_player_id}-${slots[selected.id].slug}?returnTo=${encodeURIComponent("/fc27/squad-builder")}`}>{c.view}</Link></footer>}</div></div>}</div></main>}
