"use client";
import {useEffect,useState} from "react";
type RequestInfo={user_code:string;client_type:string;client_version:string|null;status:string;expires_at:string};
export function DeviceApproval({initialCode}:{initialCode:string}){
  const[code,setCode]=useState(initialCode),[info,setInfo]=useState<RequestInfo|null>(null),[status,setStatus]=useState<"idle"|"loading"|"ready"|"done"|"error">(initialCode?"loading":"idle"),[message,setMessage]=useState("");
  async function lookup(){setStatus("loading");setMessage("");const response=await fetch(`/api/auth/device/approval?code=${encodeURIComponent(code)}`,{cache:"no-store"});if(!response.ok){setStatus("error");setMessage("That device code is invalid or expired.");return}setInfo(await response.json());setStatus("ready")}
  useEffect(()=>{if(!initialCode)return;const controller=new AbortController();fetch(`/api/auth/device/approval?code=${encodeURIComponent(initialCode)}`,{cache:"no-store",signal:controller.signal}).then(async response=>({ok:response.ok,body:response.ok?await response.json() as RequestInfo:null})).then(({ok,body})=>{if(ok&&body){setInfo(body);setStatus("ready")}else{setStatus("error");setMessage("That device code is invalid or expired.")}}).catch(error=>{if(error instanceof Error&&error.name!=="AbortError"){setStatus("error");setMessage("Unable to check that device code.")}});return()=>controller.abort()},[initialCode]);
  async function decide(action:"APPROVE"|"DENY"){setStatus("loading");const response=await fetch("/api/auth/device/approval",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({user_code:code,action})});const body=await response.json().catch(()=>({})) as{error?:string};if(!response.ok){setStatus("error");setMessage(body.error==="password_recovery_required"?"Complete your FUT Forge password recovery before approving a device.":"This request can no longer be approved.");return}setStatus("done");setMessage(action==="APPROVE"?"Device approved. You can return to the application.":"Device request denied.")}
  const input="min-h-12 w-full rounded-xl border border-white/10 bg-white/[.03] px-4 text-center font-mono text-lg uppercase tracking-[.18em] text-white focus:border-lime/40 focus:outline-none";
  return <div className="glass mt-8 rounded-2xl p-6 sm:p-8"><label htmlFor="device-code" className="text-xs font-semibold uppercase tracking-[.1em] text-white/50">Device code</label><div className="mt-3 flex gap-3"><input id="device-code" value={code} onChange={event=>setCode(event.target.value.toUpperCase())} className={input} maxLength={9} autoComplete="one-time-code"/><button className="button-primary" onClick={()=>void lookup()} disabled={status==="loading"}>Continue</button></div>{info&&status!=="done"&&<div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-5"><p className="text-sm text-white/60">A <strong className="text-white">{info.client_type}</strong> client{info.client_version?` (${info.client_version})`:""} is requesting access.</p><p className="mt-3 font-mono text-2xl tracking-[.18em] text-lime">{info.user_code}</p><p className="mt-2 text-xs text-white/40">Approve only if this code matches the application in front of you. FUT Forge will never ask for your password here.</p><div className="mt-5 flex gap-3"><button className="button-primary" onClick={()=>void decide("APPROVE")} disabled={status==="loading"||info.status!=="PENDING"}>Approve</button><button className="button-secondary" onClick={()=>void decide("DENY")} disabled={status==="loading"||info.status!=="PENDING"}>Deny</button></div></div>}{message&&<p role="status" className={`mt-5 text-sm ${status==="error"?"text-red-300":"text-lime"}`}>{message}</p>}</div>;
}
