import { NextResponse } from "next/server";
import { AdminAccessError,requireClerkAdmin } from "@/lib/auth/admin-gateway";
import { FEATURE_IDS } from "@/lib/entitlements";

type Context={params:Promise<{id:string}>};
const NO_STORE={"cache-control":"private, no-store, max-age=0"} as const;
export async function GET(_:Request,{params}:Context){try{const {id}=await params;const {actor,repository}=await requireClerkAdmin();const [user,overrides,audit]=await Promise.all([repository.getAdminUser(actor.id,id),repository.getAdminOverrides(actor.id,id),repository.getAdminAudit(actor.id,id)]);if(!user)return NextResponse.json({error:"User not found"},{status:404,headers:NO_STORE});return NextResponse.json({user,overrides,audit},{headers:NO_STORE})}catch(error){return failure(error)}}
export async function PATCH(request:Request,{params}:Context){try{const {id}=await params;const {actor,repository}=await requireClerkAdmin();const body=await request.json() as Record<string,unknown>;switch(body.action){case"role":if(body.value!=="USER"&&body.value!=="ADMIN")return invalid();await repository.adminSetRole(actor.id,id,body.value);break;case"tier":if(body.value!=="FREE"&&body.value!=="PREMIUM")return invalid();await repository.adminSetTier(actor.id,id,body.value);break;case"username":if(typeof body.value!=="string")return invalid();await repository.adminSetUsername(actor.id,id,body.value);break;case"entitlement":if(typeof body.featureId!=="string"||!FEATURE_IDS.includes(body.featureId as never)||!(["DEFAULT","ENABLED","DISABLED"] as unknown[]).includes(body.value))return invalid();await repository.adminSetEntitlement(actor.id,id,body.featureId,body.value as "DEFAULT"|"ENABLED"|"DISABLED");break;default:return invalid()}return NextResponse.json({ok:true})}catch(error){return failure(error)}}
function invalid(){return NextResponse.json({error:"Invalid request"},{status:400,headers:NO_STORE})}
function failure(error:unknown){if(error instanceof AdminAccessError)return NextResponse.json({error:error.status===503?"Admin service unavailable":"Access denied"},{status:error.status,headers:NO_STORE});const message=error instanceof Error?error.message:"";if(message==="INVALID_USERNAME")return NextResponse.json({error:"Invalid username"},{status:400,headers:NO_STORE});if(message==="ADMIN_MUTATION_REJECTED")return NextResponse.json({error:"Change rejected; the final administrator cannot be removed"},{status:409,headers:NO_STORE});if(message.includes("UNIQUE constraint failed"))return NextResponse.json({error:"Value already in use"},{status:409,headers:NO_STORE});return NextResponse.json({error:"Admin service unavailable"},{status:503,headers:NO_STORE})}
