/* eslint-disable @typescript-eslint/no-explicit-any */
import {calculateMetaRating,type Fc27MetaPlayer,type MetaRole} from "../../src/lib/fc27/meta-rating";
type MetaPlayer=Fc27MetaPlayer&{preferred_foot_code:number|null;detailed_attributes:Record<string,{value?:number}>;goalkeeping:unknown};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://axjuxmjoowrzmvyhbdhv.supabase.co";
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"sb_publishable_bMremihmEy34CWp5rG6M-g_UuysymCX";
const select="ea_player_id,display_name,overall,position_short_label,pace,shooting,passing,dribbling,defending,physicality,skill_moves_raw,weak_foot,preferred_foot_code,detailed_attributes,goalkeeping";
async function load(){const out:MetaPlayer[]=[];for(let offset=0;;offset+=1000){const q=new URLSearchParams({select,order:"ea_player_id.asc",offset:String(offset),limit:"1000"});const r=await fetch(url+"/rest/v1/fc27_players?"+q,{headers:{apikey:key,Authorization:"Bearer "+key}});if(!r.ok)throw new Error(String(r.status));const rows=await r.json() as MetaPlayer[];out.push(...rows);if(rows.length<1000)break}return out}
const t0=performance.now(),players=await load(),fetchMs=performance.now()-t0,t1=performance.now();
const scored=players.map(player=>{const rating=calculateMetaRating(player);return rating?{player,...rating,gap:rating.meta-player.overall}:null}).filter((x):x is NonNullable<typeof x>=>x!==null);const calcMs=performance.now()-t1;
const sorted=[...scored].sort((a,b)=>b.meta-a.meta||b.rawMeta-a.rawMeta||b.player.overall-a.player.overall||a.player.display_name.localeCompare(b.player.display_name)||a.player.ea_player_id-b.player.ea_player_id);
const simple=(x:any)=>({player:x.player.display_name,ovr:x.player.overall,pos:x.player.position_short_label,role:x.role,meta:x.meta,gap:x.gap,raw:x.rawMeta});
const scores=sorted.map(x=>x.meta).sort((a,b)=>a-b),pct=(p:number)=>scores[Math.floor((scores.length-1)*p)],bands={"95+":0,"90-94":0,"85-89":0,"80-84":0,"75-79":0,"70-74":0,"<70":0};
for(const s of scores){if(s>=95)bands["95+"]++;else if(s>=90)bands["90-94"]++;else if(s>=85)bands["85-89"]++;else if(s>=80)bands["80-84"]++;else if(s>=75)bands["75-79"]++;else if(s>=70)bands["70-74"]++;else bands["<70"]++}
const roles=["ST_CF","WIDE","CAM","CM","CDM","FULLBACK","CB","GK"] as MetaRole[];
const byRole=Object.fromEntries(roles.map(role=>[role,sorted.filter(x=>x.role===role).slice(0,10).map(simple)]));
const roleBands=Object.fromEntries(roles.map(role=>{const xs=sorted.filter(x=>x.role===role);return[role,{count:xs.length,avg:+(xs.reduce((s,x)=>s+x.meta,0)/xs.length).toFixed(2),top:xs[0]?.meta}]}));
const validationNames=["Kylian Mbappé","Erling Haaland","Alexia Putellas","Aitana Bonmatí","Vinícius Jr.","Ousmane Dembélé","Mohamed Salah","Rodri","Pedri","Jude Bellingham","Virgil van Dijk","William Saliba","Theo Hernández","Achraf Hakimi","Thibaut Courtois","Alisson","Mohamed Amoura","Yankuba Minteh","Allan Saint-Maximin","Gerso"];
const auditKeys=["acceleration","sprint_speed","positioning","finishing","shot_power","long_shots","volleys","penalties","vision","crossing","free_kick_accuracy","short_passing","long_passing","curve","agility","balance","reactions","ball_control","dribbling","composure","interceptions","heading_accuracy","defensive_awareness","standing_tackle","sliding_tackle","jumping","stamina","strength","aggression"];
const missing=Object.fromEntries(auditKeys.map(k=>[k,players.filter(p=>p.position_short_label!=="GK"&&p.detailed_attributes[k]?.value==null).length]));
const low={bronze:sorted.filter(x=>x.player.overall<=64).slice(0,5).map(simple),silver:sorted.filter(x=>x.player.overall>=65&&x.player.overall<=74).slice(0,5).map(simple),gold80:sorted.filter(x=>x.player.overall>=75&&x.player.overall<=80).slice(0,10).map(simple)};
console.log(JSON.stringify({performance:{players:players.length,fetchMs:+fetchMs.toFixed(1),calculationMs:+calcMs.toFixed(1),perPlayerUs:+(calcMs*1000/players.length).toFixed(2)},audit:{outfield:players.filter(p=>p.position_short_label!=="GK").length,gk:players.filter(p=>p.position_short_label==="GK").length,missing,faceMissing:Object.fromEntries(["pace","shooting","passing","dribbling","defending","physicality"].map(k=>[k,players.filter(p=>(p as any)[k]==null).length])),abilitiesNonEmpty:0},distribution:{count:scores.length,min:scores[0],max:scores.at(-1),average:+(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(2),median:pct(.5),p10:pct(.1),p25:pct(.25),p75:pct(.75),p90:pct(.9),p95:pct(.95),p99:pct(.99),bands,roleBands},globalTop25:sorted.slice(0,25).map(simple),byRole,positiveGaps:[...scored].sort((a,b)=>b.gap-a.gap||b.meta-a.meta).slice(0,20).map(simple),negativeGaps:[...scored].sort((a,b)=>a.gap-b.gap||b.meta-a.meta).slice(0,20).map(simple),validation:validationNames.map(n=>scored.find(x=>x.player.display_name===n)).filter(Boolean).map(simple),low},null,2));
