/* eslint-disable @typescript-eslint/ban-ts-comment, @typescript-eslint/no-explicit-any */
// @ts-nocheck -- controlled offline generator validates its untrusted JSON input at runtime.
import { createHash } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { calculateMetaRating } from "../../src/lib/fc27/meta-rating.ts";
import { scoreHiddenGem } from "../../src/lib/fc27/hidden-gems-shared.ts";

const EXPECTED_COUNT=20_689,SHARD_SIZE=128,SITEMAP_SIZE=5_000,SCHEMA_VERSION=1;
const root=process.cwd(),sourcePath=path.join(root,"data/fc27/normalized/fc27-players.json"),publicRoot=path.join(root,"public/fc27-data");
type Obj=Record<string,any>;
const stable=(v:any):string=>v===null||typeof v!=="object"?JSON.stringify(v):Array.isArray(v)?`[${v.map(stable).join(",")}]`:`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;
const hash=(v:string)=>createHash("sha256").update(v).digest("hex");
const fold=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const iso=(v:string)=>{const m=v?.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})\s/);return m?`${m[3]}-${m[1].padStart(2,"0")}-${m[2].padStart(2,"0")}`:null};
function flatten(p:Obj){const f=p.face_stats,b=p.bio,a=p.affiliation,i=p.identity,pos=p.position;return{
 ea_player_id:i.ea_player_id,slug:i.slug,first_name:i.first_name,last_name:i.last_name,common_name:i.common_name,display_name:i.display_name,
 overall:p.ratings.overall,rank:p.ratings.rank,pace:f.pace?.value??null,shooting:f.shooting?.value??null,passing:f.passing?.value??null,dribbling:f.dribbling?.value??null,defending:f.defending?.value??null,physicality:f.physicality?.value??null,
 face_stat_diffs:{pace:f.pace?.diff??0,shooting:f.shooting?.diff??0,passing:f.passing?.diff??0,dribbling:f.dribbling?.diff??0,defending:f.defending?.diff??0,physicality:f.physicality?.diff??0},
 position_id:pos.position_id,position_short_label:pos.position,position_label:pos.position_label,position_type_id:pos.position_type_id,position_type_name:pos.position_type_name,alternate_positions:pos.alternate_positions,
 nationality_id:a.nationality_id,nationality_name:a.nationality_name,nationality_image_url:a.nationality_image_url,club_id:a.club_id,club_name:a.club_name,club_image_url:a.club_image_url,league_name:a.league_name||null,
 birthdate:iso(b.birthdate_raw),skill_moves_raw:b.skill_moves_raw,weak_foot:b.weak_foot,preferred_foot_code:b.preferred_foot_code,height_cm:b.height_raw?Number(b.height_raw):null,weight_kg:b.weight_raw?Number(b.weight_raw):null,
 detailed_attributes:p.detailed_attributes,goalkeeping:p.goalkeeping,player_abilities_raw:p.player_abilities_raw,avatar_url:p.media.avatar_url};}
const ranking=(p:Obj)=>({ea_player_id:p.ea_player_id,slug:p.slug,display_name:p.display_name,overall:p.overall,position_short_label:p.position_short_label,nationality_name:p.nationality_name,nationality_image_url:p.nationality_image_url,club_name:p.club_name,club_image_url:p.club_image_url,league_name:p.league_name,avatar_url:p.avatar_url,pace:p.pace,shooting:p.shooting,passing:p.passing,dribbling:p.dribbling,defending:p.defending,physicality:p.physicality});
async function put(base:string,rel:string,value:any){const target=path.join(base,rel);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,stable(value));return rel.replaceAll("\\","/");}
async function main(){const raw=await readFile(sourcePath,"utf8"),parsed=JSON.parse(raw),input=parsed.players;if(!Array.isArray(input)||input.length!==EXPECTED_COUNT)throw new Error(`Expected ${EXPECTED_COUNT} players, got ${input?.length}`);
 const ids=new Set<number>();for(const p of input){const id=p?.identity?.ea_player_id;if(!Number.isSafeInteger(id)||ids.has(id))throw new Error(`Invalid/duplicate player ID ${id}`);ids.add(id);for(const key of ["display_name","slug"]){if(!p.identity[key])throw new Error(`Player ${id} missing ${key}`)}if(!p.ratings||!p.position||!p.affiliation||!p.face_stats||!p.detailed_attributes||!p.bio||!p.media)throw new Error(`Player ${id} has invalid schema`)}
 const checksum=hash(raw),version=`v1-${checksum.slice(0,12)}`,tmp=path.join(publicRoot,`.${version}.tmp`),dest=path.join(publicRoot,version);await rm(tmp,{recursive:true,force:true});await mkdir(tmp,{recursive:true});const players=input.map(flatten).sort((a:Obj,b:Obj)=>a.ea_player_id-b.ea_player_id),index:Record<string,number>={};
 const artifacts:any={players:[],search:[],rankings:{},entities:{},positions:"positions/counts.json",filters:"filters/options.json",sitemaps:[],meta:"meta/rankings.json",hiddenGems:"hidden-gems/default.json"};
 for(let n=0;n<players.length;n+=SHARD_SIZE){const shard=players.slice(n,n+SHARD_SIZE),no=n/SHARD_SIZE,rel=`players/shard-${String(no).padStart(3,"0")}.json`;for(const p of shard)index[p.ea_player_id]=no;artifacts.players.push(await put(tmp,rel,shard))}await put(tmp,"players/index.json",index);
 const search=new Map<string,number[]>(),searchRows=[];for(const p of players){const normalized=fold(p.display_name);searchRows.push({ea_player_id:p.ea_player_id,slug:p.slug,display_name:p.display_name,first_name:p.first_name,last_name:p.last_name,common_name:p.common_name,normalized_name:normalized,overall:p.overall,position_short_label:p.position_short_label,club_name:p.club_name,nationality_name:p.nationality_name});const prefixes=new Set(fold([p.first_name,p.last_name,p.common_name,p.display_name].filter(Boolean).join(" ")).split(/[\s\-']+/).filter(Boolean).map((word:string)=>/^[a-z]/.test(word)?word[0]:"other"));for(const prefix of prefixes)search.set(prefix,[...(search.get(prefix)??[]),p.ea_player_id])}await put(tmp,"search/index.json",searchRows);for(const [prefix,ids]of [...search].sort())artifacts.search.push(await put(tmp,`search/${prefix}.json`,ids));
 const statMap:any={overall:"overall",pace:"pace",shooting:"shooting",passing:"passing",dribbling:"dribbling",defending:"defending",physical:"physicality"};for(const [name,field]of Object.entries(statMap)){const rows=players.filter((p:Obj)=>name==="overall"||p.position_short_label!=="GK").sort((a:Obj,b:Obj)=>(b[field as string]??-1)-(a[field as string]??-1)||b.overall-a.overall||a.display_name.localeCompare(b.display_name)||a.ea_player_id-b.ea_player_id).slice(0,50).map(ranking);artifacts.rankings[name]=await put(tmp,`rankings/${name}.json`,rows)}
 const entityCfg:any={nations:"nationality_name",clubs:"club_name",leagues:"league_name"};for(const [kind,field]of Object.entries(entityCfg)){const counts=new Map<string,number>();for(const p of players){const v=p[field as string];if(v)counts.set(v,(counts.get(v)??0)+1)}const rows=[...counts].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));artifacts.entities[kind]=await put(tmp,`entities/${kind}.json`,rows)}
 const counts=new Map<string,number>();for(const p of players)counts.set(p.position_short_label,(counts.get(p.position_short_label)??0)+1);await put(tmp,artifacts.positions,[...counts].map(([position,count])=>({position,count})));
 await put(tmp,artifacts.filters,{nations:[...new Set(players.map((p:Obj)=>p.nationality_name))].sort(),leagues:[...new Set(players.map((p:Obj)=>p.league_name).filter(Boolean))].sort(),positions:[...counts.keys()]});
 for(let n=0;n<players.length;n+=SITEMAP_SIZE)artifacts.sitemaps.push(await put(tmp,`sitemaps/players-${n/SITEMAP_SIZE+1}.json`,players.slice(n,n+SITEMAP_SIZE).map((p:Obj)=>({ea_player_id:p.ea_player_id,slug:p.slug}))));
 const meta=players.flatMap((p:Obj)=>{const x=calculateMetaRating(p);return x?[{...ranking(p),skill_moves_raw:p.skill_moves_raw,weak_foot:p.weak_foot,player_abilities_raw:p.player_abilities_raw,base_meta_rating:x.meta}]:[]}).sort((a:Obj,b:Obj)=>b.base_meta_rating-a.base_meta_rating||b.overall-a.overall||a.display_name.localeCompare(b.display_name)||a.ea_player_id-b.ea_player_id);await put(tmp,artifacts.meta,meta);
 const gems=players.flatMap((p:Obj)=>{const x=scoreHiddenGem(p);return x?[x]:[]}).sort((a:Obj,b:Obj)=>b.score-a.score||a.player.overall-b.player.overall||a.player.ea_player_id-b.player.ea_player_id);await put(tmp,artifacts.hiddenGems,gems);
 const dataset={schemaVersion:SCHEMA_VERSION,datasetVersion:version,generatedAt:new Date().toISOString(),playerCount:players.length,checksum:`sha256:${checksum}`,shardSize:SHARD_SIZE,shardCount:Math.ceil(players.length/SHARD_SIZE),artifacts};await put(tmp,"dataset.json",dataset);await rm(dest,{recursive:true,force:true});await rename(tmp,dest);await mkdir(publicRoot,{recursive:true});await writeFile(path.join(publicRoot,"manifest.json"),stable(dataset));console.log(JSON.stringify(dataset,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
